### ISSUE TITLE
Miniget Error

### ISSUE THREAD

**Issue by Moazlion** [eritislami/evobot#1046]
Miniget error
It spams the discord server channel with a error code of 410

It happened before but it got fixed and then it didnt spam the server but now its doing the same thing

It only does this when u start to play music the help ping and invite command ork just fine
this is the error:

`MinigetError: Status code: 410
    at ClientRequest.<anonymous> (/home/runner/Moaz-music/node_modules/miniget/dist/index.js:210:27)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at HTTPParser.parserOnIncomingClient (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at TLSSocket.socketOnData (_http_client.js:474:22)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:297:12) {
  statusCode: 410
}
`
Node version is **v12.16.1**

I checked all other closed issues regarding this but it didn’t help

**Comment by AbelCode1** [comment]
Change youtube API key

**Comment by Moazlion** [comment]
Thank you now every time i get this error i’ll just do what u told me
