### ISSUE TITLE
Bug: the bot can't       use                      the                   YouTubeAPI

### ISSUE THREAD

**Issue by bigkitttty** [eritislami/evobot#1069]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1.typ in your YouTubeAPI
2.  it     sys      rror: The YouTube API key you provided was not a string.
    at new YouTube (/home/runner/bk-bot-11/node_modules/simple-youtube-api/src/index.js:26:44)
    at Object.<anonymous> (/home/runner/bk-bot-11/commands/play.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/bk-bot-11/index.js:37:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! evobot@0.15.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the evobot@0.15.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-12-24T21_04_14_349Z-debug.log
exit status 1              
 
**Expected behavior**
A description of what you expected to happen.
log in to the  key and i can                  use                    the           bot
**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by Velosofy** [comment]
I've done this before, and its due my own error that i copy-pasted the wrong token..
Maybe you should do a double-check...
