### ISSUE TITLE
Bug:Type error

### ISSUE THREAD

**Issue by Shaxpartan** [eritislami/evobot#1078]
TypeError: command.execute is not a function
    at Client.<anonymous> (/home/container/index.js:132:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 

I get this error

**Comment by wolf-yuan-6115** [comment]
Your code should be
```js
module.exports = {
  name: "lock-channel",
  description: "locks a Channel",
  category: "admin",
  P_user: ["MANAGE_CHANNELS"],
  P_bot: ["MANAGE_CHANNELS"],
  execute: async (client, message, args) => {
    message.channel.permissionOverwrites.edit(message.guild.id, {
      SEND_MESSAGES: false
    });
    const embed = new Discord.MessageEmbed()
      .setTitle("Channel Updates")
      .setDescription(🔒$ {
          message.channel
        }
        has been locked)
      .setColor("RANDOM");
    await message.channel.send({
      embeds: [embed]
    });
    message.delete();
  }
}
```

Evobot will find `execute` function in your command file, not `run`
