### ISSUE TITLE
Bug: Music won't play - Cannot find module 'node-opus'

### ISSUE THREAD

**Issue by FugiMuffi** [eritislami/evobot#1142]
**Describe the bug**
Evobot (in docker) won't play any song from youtube, throws an error in console when invoked.

**How To Reproduce**
1. Run docker container (with any tag > 1.0.0)
2. Try to /play a song
3. Observe: Bot joins the channel, but does not play or send any message in chat
(see stack trace below)
 
**Expected behavior**
The bot should start playing the requested song and announce this in chat.

**Environment (add if possible)**
* Docker: 1.0.4, 1.0.7, 1.1.0, 1.1.1, 1.2.0, 1.2.1 (latest) as well as built from master myself

**Additional information & screenshots**
Tags 1.0.0 and older work as expected.

<details>
  <summary>stack trace</summary>
  
```
/home/evobot/node_modules/prism-media/src/util/loader.js:12
  throw new Error(errorLog.join('\n'));
        ^

Error: Error: Cannot find module '/home/evobot/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.28/opus.node'
Require stack:
- /home/evobot/node_modules/@discordjs/opus/lib/index.js
- /home/evobot/node_modules/prism-media/src/util/loader.js
- /home/evobot/node_modules/prism-media/src/opus/Opus.js
- /home/evobot/node_modules/prism-media/src/opus/index.js
- /home/evobot/node_modules/prism-media/src/index.js
- /home/evobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/evobot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/evobot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/evobot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/evobot/node_modules/discord.js/src/client/Client.js
- /home/evobot/node_modules/discord.js/src/index.js
- /home/evobot/index.js
Error: Cannot find module 'node-opus'
Require stack:
- /home/evobot/node_modules/prism-media/src/util/loader.js
- /home/evobot/node_modules/prism-media/src/opus/Opus.js
- /home/evobot/node_modules/prism-media/src/opus/index.js
- /home/evobot/node_modules/prism-media/src/index.js
- /home/evobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/evobot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/evobot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/evobot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/evobot/node_modules/discord.js/src/client/Client.js
- /home/evobot/node_modules/discord.js/src/index.js
- /home/evobot/index.js
Error: Cannot find module 'opusscript'
Require stack:
- /home/evobot/node_modules/prism-media/src/util/loader.js
- /home/evobot/node_modules/prism-media/src/opus/Opus.js
- /home/evobot/node_modules/prism-media/src/opus/index.js
- /home/evobot/node_modules/prism-media/src/index.js
- /home/evobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/evobot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/evobot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/evobot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/evobot/node_modules/discord.js/src/client/Client.js
- /home/evobot/node_modules/discord.js/src/index.js
- /home/evobot/index.js
    at Object.loader [as require] (/home/evobot/node_modules/prism-media/src/util/loader.js:12:9)
    at loadOpus (/home/evobot/node_modules/prism-media/src/opus/Opus.js:17:17)
    at new OpusStream (/home/evobot/node_modules/prism-media/src/opus/Opus.js:46:10)
    at new Decoder (/home/evobot/node_modules/prism-media/src/opus/Opus.js:183:1)
    at AudioPlayer.playOpusStream (/home/evobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js:73:23)
    at VoiceConnection.play (/home/evobot/node_modules/discord.js/src/client/voice/util/PlayInterface.js:75:28)
    at play (/home/evobot/include/play.js:61:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

</details>
<details>
  <summary>docker-compose.yml</summary>

```yml
version: "3.9"

services:
  evobot:
    image: eritislami/evobot
    container_name: evobot
    restart: unless-stopped
    environment:
    - TOKEN=...
    - YOUTUBE_API_KEY=...
    - SOUNDCLOUD_CLIENT_ID=
    - MAX_PLAYLIST_SIZE=100
    - PREFIX=+
    - PRUNING=false
    - LOCALE=en
    - DEFAULT_VOLUME=100
    - STAY_TIME=120
```

</details>

**Comment by eritislami** [comment]
Can you please try by running `docker run -e "TOKEN=your-token" eritislami/evobot`

<img width="842" alt="Screenshot 2022-05-01 at 15 20 57" src="https://user-images.githubusercontent.com/22680785/166147853-eee07177-a4a2-4fc4-ba51-d0e4e1f8e48d.png">

It's running fine for me

**Comment by FugiMuffi** [comment]
That command is working for me as well. Oddly enough, I can't reproduce the error anymore using the exact same test setup from before...
