### ISSUE TITLE
Bug: Manually deleting video preview embed message results in crash

### ISSUE THREAD

**Issue by SugarD-x** [eritislami/evobot#1151]
**Describe the bug**
When manually deleting a video preview embed message, (tested here after stopping music play), the bot crashes with the following error information:

````
DiscordAPIError: Unknown Message
    at RequestHandler.execute (evobot-1.2.2\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (evobot-1.2.2\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async ReactionManager.removeAll (evobot-1.2.2\node_modules\discord.js\src\managers\ReactionManager.js:61:5) {
  method: 'delete',
  path: '/channels/REDACTED/messages/REDACTED/reactions',
  code: 10008,
  httpStatus: 404,
  requestData: { json: undefined, files: [] }
}
evobot-1.2.2\node_modules\discord.js\src\rest\RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Unknown Message
    at RequestHandler.execute (evobot-1.2.2\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (evobot-1.2.2\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async MessageManager.delete (evobot-1.2.2\node_modules\discord.js\src\managers\MessageManager.js:210:5)
    at async Message.delete (evobot-1.2.2\node_modules\discord.js\src\structures\Message.js:792:5) {
  method: 'delete',
  path: '/channels/REDACTED/messages/REDACTED',
  code: 10008,
  httpStatus: 404,
  requestData: { json: undefined, files: [] }
}

Node.js v17.6.0
````

**How To Reproduce**
1. Play music and allow the bot to embed the video preview from YouTube in a message.
2. Stop the music. (Haven't tested if this is a requirement to reproduce or not).
3. Manually delete the video preview embed message.
4. Check the console for the error information.
 
**Expected behavior**
The bot does not crash or throw any errors.

**Environment (add if possible)**
* Node.js version: 17.6.0

**Additional information & screenshots**
Appears to happen consistently with the latest release package for the bot. Only code changes made so far were from pull request #1148 so the bot would work properly on Windows.

**Comment by eritislami** [comment]
Yes this makes sense, the bot has to use the message as a reference to the other objects, the guild, the user etc..., need to add something to handle this case

**Comment by eritislami** [comment]
I believe this should be fixed in the typescript version which is coming soon

https://github.com/eritislami/evobot/tree/refactor/typescript
