### ISSUE TITLE
Bug: node-ytdl-core

### ISSUE THREAD

**Issue by Cptnmo109** [eritislami/evobot#1241]
**Describe the bug**
since yesterday when i tried to use the play command it returned this in the console

```
SyntaxError: Missing catch or finally after try
    at new Script (node:vm:100:7)
    at Object.exports.decipherFormats (/home/runner/evobot/node_modules/ytdl-core/lib/sig.js:116:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async exports.getInfo (/home/runner/evobot/node_modules/ytdl-core/lib/info.js:401:17)
```

**How To Reproduce**
just do prefix play song name

**Comment by 0xGingi** [comment]
Did you find a solution, having the same error

**Comment by Cptnmo109** [comment]
> Did you find a solution, having the same error

Go to package.json change the ytdl version to 4.10.0

Delete package-lock.json

>Run `npm install ytdl-core@4.10.0`

Restart the bot

If you still have the problem dm me through discord  > @L U C I D#1467
