### ISSUE TITLE
Bug: Missing catch or finally after try

### ISSUE THREAD

**Issue by mohamedgentle** [eritislami/evobot#1243]
when using tha bot = "Missing catch or finally after try"

**Comment by markodowd** [comment]
I'd same problem for game night so downgrading ytdl-core has fixed it for the moment.

``` "ytdl-core": "4.9.1", ```

**Comment by Gamebuster19901** [comment]
Same issue, here is the stacktrace:

```
Aug 20 17:44:28 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[48087]: > evobot@2.0.0 start
Aug 20 17:44:28 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[48087]: > ts-node index.ts
Aug 20 17:44:31 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[48099]: Tune ready!
Aug 20 17:44:43 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[48099]: evalmachine.<anonymous>:24
Aug 20 17:44:43 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[48099]: c[72],c[6]),(0,c[85])(c[11]),(0,c[41])(c[39],c[28],(0,c[66])()),(0,c[78])(c[Math.pow(6,2)+122+-119],c[new Date("Wednesday December 31 1969 19:00:14 CDT")/1E3])}catch(d){(0<c[0]||(((0,c[80])(c[60],c[88]),c[80])(c[21],c[88]),0))&&(0,c[17])((0,c[70])(c[6]),c[78],c[88],c[12])}try{2<c[91]&&(1<c[53]?(0,c[17])((0,c[80])(c[82],c[6]),c[78],c[39],c[5]):((0,c[45])(c[49],c[88]),c[78])(c[88],c[86])),(0,c[17])((0,c[85])(c[31]),c[41],c[88],c[75],(0,c[35])())}catch(d){}};Wka(ncode);
Aug 20 17:44:43 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[48099]:                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ^
Aug 20 17:44:43 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[48099]: SyntaxError: Missing catch or finally after try
Aug 20 17:44:43 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[48099]:     at new Script (node:vm:100:7)
Aug 20 17:44:43 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[48099]:     at Object.exports.decipherFormats (/home/gamebuster/Desktop/Modding/evobot/node_modules/ytdl-core/lib/sig.js:116:51)
Aug 20 17:44:43 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[48099]:     at runMicrotasks (<anonymous>)
Aug 20 17:44:43 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[48099]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Aug 20 17:44:43 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[48099]:     at async Promise.all (index 0)
Aug 20 17:44:43 gamebuster-Ryzen9-3900X-RTX-3080 start.sh[48099]:     at async exports.getInfo (/home/gamebuster/Desktop/Modding/evobot/node_modules/ytdl-core/lib/info.js:401:17)

```

**Comment by Cptnmo109** [comment]
> when using tha bot = "Missing catch or finally after try"

you can fix it by changing the youtube-dl version to 4.10.0 inside the package.json and delete the package-lock.json, run 

> `npm install ytdl-core@4.10.0` 

 and after that just restart the bot

**Comment by eritislami** [comment]
36ef0c282b6557f338843f3c79ee9e6a90205f3a

Reinstall your npm packages to get the fix
