### ISSUE TITLE
🐛 `RangeError [BitFieldInvalid]: Invalid bitfield flag or number: CONNECT.`

### ISSUE THREAD

**Issue by ivirtex** [eritislami/evobot#1345]
**Describe the bug**
An error occurs when executing `!p` command:
```
RangeError [BitFieldInvalid]: Invalid bitfield flag or number: CONNECT.
    at Function.resolve (/home/ubuntu/jm3/evobot/node_modules/discord.js/src/util/BitField.js:168:11)
    at /home/ubuntu/jm3/evobot/node_modules/discord.js/src/util/BitField.js:163:54
    at Array.map (<anonymous>)
    at Function.resolve (/home/ubuntu/jm3/evobot/node_modules/discord.js/src/util/BitField.js:163:40)
    at new BitField (/home/ubuntu/jm3/evobot/node_modules/discord.js/src/util/BitField.js:33:38)
    at new PermissionsBitField (/home/ubuntu/jm3/evobot/node_modules/discord.js/src/util/PermissionsBitField.js:12:1)
    at PermissionsBitField.missing (/home/ubuntu/jm3/evobot/node_modules/discord.js/src/util/BitField.js:71:12)
    at PermissionsBitField.missing (/home/ubuntu/jm3/evobot/node_modules/discord.js/src/util/PermissionsBitField.js:72:83)
    at checkPermissions (/home/ubuntu/jm3/evobot/utils/checkPermissions.ts:15:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'BitFieldInvalid'
}
```

There's probably some code not yet migrated to v14.
https://discordjs.guide/additional-info/changes-in-v14.html#enum-values

**How To Reproduce**
1. `npm run prod`
2. `!p whatever`

**Expected behavior**
Plays song without errors

**Environment (add if possible)**
* Node.js version: v16.17.0

**Comment by eritislami** [comment]
I believe you are correct, for now, you can fix your problem by giving your bot the required permissions to run the commands, for play they are: ["CONNECT", "SPEAK", "ADD_REACTIONS", "MANAGE_MESSAGES"]
