### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by devilmk666** [eritislami/evobot#1347]
Just pulled it into docker swarm, it throws following error into logs:

> evobot@2.5.1 prod
> npm run build && node ./dist/index.js
> evobot@2.5.1 build
> tsc --build
evobot ready!
RangeError [BitFieldInvalid]: Invalid bitfield flag or number: CONNECT.
    at Function.resolve (/home/evobot/node_modules/discord.js/src/util/BitField.js:168:11)
    at /home/evobot/node_modules/discord.js/src/util/BitField.js:163:54
    at Array.map (<anonymous>)
    at Function.resolve (/home/evobot/node_modules/discord.js/src/util/BitField.js:163:40)
    at new BitField (/home/evobot/node_modules/discord.js/src/util/BitField.js:33:38)
    at new PermissionsBitField (/home/evobot/node_modules/discord.js/src/util/PermissionsBitField.js:12:1)
    at PermissionsBitField.missing (/home/evobot/node_modules/discord.js/src/util/BitField.js:71:12)
    at PermissionsBitField.missing (/home/evobot/node_modules/discord.js/src/util/PermissionsBitField.js:72:83)
    at checkPermissions (/home/evobot/dist/utils/checkPermissions.js:9:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'BitFieldInvalid'
}
      [Symbol(kCapture)]: false
    },
    playbackDuration: 0,
    started: false,
    silencePaddingFrames: 5,
    silenceRemaining: -1
  }
}
WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".
AudioPlayerError: Status code: 403
    at ClientRequest.<anonymous> (/home/evobot/node_modules/miniget/dist/index.js:206:27)
    at Object.onceWrapper (node:events:646:26)
    at ClientRequest.emit (node:events:526:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:618:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (node:_http_client:482:22)
    at TLSSocket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  resource: AudioResource {
    playStream: Encoder {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
> evobot@2.5.1 prod
      encoder: null,
> npm run build && node ./dist/index.js
      _options: [Object],
> evobot@2.5.1 build
> tsc --build
npm notice 
npm notice New major version of npm available! 8.5.0 -> 9.4.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.4.1>
npm notice Run `npm install -g npm@9.4.1` to update!
npm notice 
npm ERR! path /home/evobot
npm ERR! command failed
      _required: 3840,
      _buffer: null,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null
    },
    edges: [ [Object], [Object], [Object] ],
    metadata: Song {
      url: 'https://www.youtube.com/watch?v=oDHAEME84Og',
      title: 'Crystal Castles - Untrust Us',
      duration: 187
    },
    volume: VolumeTransformer {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      _readInt: [Function (anonymous)],
      _writeInt: [Function (anonymous)],
      _bits: 16,
      _bytes: 2,
      _extremum: 32768,
      volume: 1,
      _chunk: null,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null
    },
    encoder: Encoder {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      encoder: null,
      _options: [Object],
      _required: 3840,
      _buffer: null,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null
    },
    audioPlayer: AudioPlayer {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _state: [Object],
      subscribers: [Array],
      behaviors: [Object],
      debug: [Function (anonymous)],
      [Symbol(kCapture)]: false
    },
    playbackDuration: 0,
    started: false,
    silencePaddingFrames: 5,
    silenceRemaining: -1
  }
}
npm notice 
npm notice New major version of npm available! 8.5.0 -> 9.4.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.4.0>
npm notice Run `npm install -g npm@9.4.0` to update!
npm notice 
npm ERR! path /home/evobot
npm ERR! command failed
npm ERR! signal SIGTERM
npm ERR! command sh -c npm run build && node ./dist/index.js
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/evobot/.npm/_logs/2023-02-01T08_46_01_403Z-debug-0.log
npm ERR! signal SIGTERM
npm ERR! command sh -c npm run build && node ./dist/index.js
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/evobot/.npm/_logs/2023-02-02T04_39_02_913Z-debug-0.log

**Comment by eritislami** [comment]
Sorry about this, I haven't pushed a new release for this fix, will do it now

**Comment by eritislami** [comment]
https://github.com/eritislami/evobot/actions/runs/4072598146

When this job completes you can re-run with the newest version

**Comment by devilmk666** [comment]
Thanks, works like a charm :)
