### ISSUE TITLE
Cannot read properties of null 

### ISSUE THREAD

**Issue by Bence98007** [eritislami/evobot#1367]
Hello,

I'm trying out this music bot, but I've already ran into an issue.
When I send any command to my bot, the console out of my docker container throws this error msg:

```
Musicbot ready!
TypeError: Cannot read properties of null (reading 'members')
    at checkPermissions (/home/evobot/dist/utils/checkPermissions.js:5:44)
    at Client.<anonymous> (/home/evobot/dist/structs/Bot.js:92:88)
    at Client.emit (node:events:526:28)
    at InteractionCreateAction.handle (/home/evobot/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at Object.module.exports [as INTERACTION_CREATE] (/home/evobot/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/evobot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/evobot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (/home/evobot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
    at callListener (/home/evobot/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/evobot/node_modules/ws/lib/event-target.js:209:9)
```

I've tried with full admin permissions as well, but didnt work. Is this a bug in the latest docker image, or what can cause this?

Thanks!!

**Comment by jaredtalon88** [comment]
I use the Docker implementation myself and haven't run into this error.

Do you have the "Privileged Gateway Intents" boxes all checked in the Discord Developer Portal for the Bot user who's token you are using in the Docker configuration?

Have you invited your Bot User to your Discord server?

Could you provide the commands being run to start the docker container?

**Comment by eritislami** [comment]
I also think this is a gateway intents related problem, otherwise would have seen this issue as well

**Comment by eritislami** [comment]
Closing for inactivity
