### ISSUE TITLE
Server issues when /play command is used. 'Missing Access' error from Discord API🐛 

### ISSUE THREAD

**Issue by mattgrunwald** [eritislami/evobot#1388]
**Describe the bug**
Server crashes when asked to play a song.

**How To Reproduce**
1. run `docker run -it --rm -e TOKEN="$TOKEN" eritislami/evobot`
2. Add the bot to your server with message content intent
3. Add permissions you think it needs, (bot and applications.commands scopes), Manage messages, voice connect and speak)
4. in your server, run `/play mr blue sky`
 
**Expected behavior**
Bot enters voice chat and plays the song

**Environment (add if possible)**
* Node.js version: 16.14 (from dockerfile)

**Additional information & screenshots**
Here's the logs of the container:
```
music_bot ready!
WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".
DiscordAPIError[50001]: Missing Access
    at SequentialHandler.runRequest (/home/evobot/node_modules/@discordjs/rest/dist/index.js:667:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/evobot/node_modules/@discordjs/rest/dist/index.js:464:14)
    at async REST.request (/home/evobot/node_modules/@discordjs/rest/dist/index.js:910:22)
    at async TextChannel.send (/home/evobot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:176:15)
    at async MusicQueue.sendPlayingMessage (/home/evobot/dist/structs/MusicQueue.js:158:30) {
  requestBody: {
    files: [],
    json: {
      content: '🎶 Started playing: **Mr. Blue Sky** https://www.youtube.com/watch?v=wuJIqmha2Hk',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined
    }
  },
  rawError: { message: 'Missing Access', code: 50001 },
  code: 50001,
  status: 403,
  method: 'POST',
  url: 'https://discord.com/api/v10/channels/<channel id omitted>/messages'
}
/home/evobot/node_modules/@discordjs/rest/dist/index.js:667
        throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
              ^

DiscordAPIError[50001]: Missing Access
    at SequentialHandler.runRequest (/home/evobot/node_modules/@discordjs/rest/dist/index.js:667:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/evobot/node_modules/@discordjs/rest/dist/index.js:464:14)
    at async REST.request (/home/evobot/node_modules/@discordjs/rest/dist/index.js:910:22)
    at async TextChannel.send (/home/evobot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:176:15) {
  requestBody: {
    files: [],
    json: {
      content: 'Missing Access',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined
    }
  },
  rawError: { message: 'Missing Access', code: 50001 },
  code: 50001,
  status: 403,
  method: 'POST',
  url: 'https://discord.com/api/v10/channels/<channel id omitted>/messages'
}
```

I've tried allowing all other permissions (except administrator) and all other intents, I still keep getting this error

**Comment by mattgrunwald** [comment]
I've also tried updating `ytdl-core` and that doesn't seem to help

**Comment by eritislami** [comment]
Nothing to do with ytdl-core, its missing permissions to send messages

**Comment by mattgrunwald** [comment]
![snip](https://user-images.githubusercontent.com/31670982/227750667-7cbf6a0d-8f52-404a-a97d-e0eed68bcf57.PNG)

These are the permissions I'm giving the bot. Shouldn't it be able to send messages then?

**Comment by mattgrunwald** [comment]
For more context the bot can send messages in its current state in my server. Using `/lyrics` causes the bot to send a correct message that there's nothing currently playing. For some reason the crash is happening when the bot tries to send the message with all the control reactions. 

When I try to use `/play` the bot does indeed join the right voice channel and the song says for half a second before cutting out.
