### ISSUE TITLE
🐛 Error: Cannot find module 'node:events' Issue 

### ISSUE THREAD

**Issue by itsmoe15** [eritislami/evobot#1398]
**Describe the bug**
When I try to run the bot on Ubuntu 22.04
it gives me this error after run `start  start run`

```
> evobot@2.7.0 start
> ts-node index.ts

Error: Cannot find module 'node:events'
Require stack:
- /home/ubuntu/discordDJ/evobot/node_modules/discord.js/src/client/BaseClient.js
- /home/ubuntu/discordDJ/evobot/node_modules/discord.js/src/index.js
- /home/ubuntu/discordDJ/evobot/index.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/ubuntu/discordDJ/evobot/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ubuntu/discordDJ/evobot/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .js] (/home/ubuntu/discordDJ/evobot/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:863:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ubuntu/discordDJ/evobot/node_modules/discord.js/src/client/BaseClient.js',
    '/home/ubuntu/discordDJ/evobot/node_modules/discord.js/src/index.js',
    '/home/ubuntu/discordDJ/evobot/index.ts'
  ]
}

```

**How To Reproduce**
just normal installation on
 1.npm version (8.5.1)
2.node version (v12.22.9)
3.Ubuntu version (22.04.2 LTS)

it gives this when i run (`npm fund`):

```
evobot@2.7.0
├── https://github.com/sponsors/sindresorhus
│   └── array-move@3.0.1, make-dir@3.1.0, strip-json-comments@3.1.1, ansi-escapes@4.3.2, type-fest@0.21.3, figures@3.2.0, ora@5.4.1, cli-spinners@2.7.0, is-unicode-supported@0.1.0, log-symbols@4.1.0, defaults@1.0.4, onetime@5.1.2
├── https://github.com/sponsors/mashpie
│   └── i18n@0.15.1
├─┬ https://opencollective.com/nodemon
│ │ └── nodemon@2.0.22
│ └── https://paulmillr.com/funding/
│     └── chokidar@3.5.3
├─┬ https://github.com/sindresorhus/file-type?sponsor=1
│ │ └── file-type@18.2.1
│ └─┬ https://github.com/sponsors/Borewit
│   │ └── readable-web-to-node-stream@3.0.2, strtok3@7.0.0, peek-readable@5.0.0, token-types@5.0.1
│   └── https://github.com/sponsors/feross
│       └── safe-buffer@5.2.1, ieee754@1.2.1, buffer@5.7.1, base64-js@1.5.1
├── https://github.com/sponsors/ljharb
│   └── minimist@1.2.7
├── https://github.com/sponsors/fb55
│   └── domelementtype@2.3.0
├── https://github.com/fb55/entities?sponsor=1
│   └── entities@2.2.0
├── https://github.com/sponsors/RubenVerborgh
│   └── follow-redirects@1.15.2
├── https://github.com/sponsors/isaacs
│   └── rimraf@3.0.2, glob@7.2.3
├── https://github.com/sponsors/jonschlinkert
│   └── picomatch@2.3.1
├─┬ https://github.com/chalk/chalk?sponsor=1
│ │ └── chalk@4.1.2
│ └── https://github.com/chalk/ansi-styles?sponsor=1
│     └── ansi-styles@4.3.0
└── https://github.com/chalk/wrap-ansi?sponsor=1
    └── wrap-ansi@7.0.0

ubuntu@vps-693d50e9:~/discordDJ/evobot$

```
 
**Expected behavior**
A description of what you expected to happen.
i expected the bot to turn on, here's a whole output of the console

```
ubuntu@vps-693d50e9:~/discordDJ$ git clone https://github.com/eritislami/evobot.git
Cloning into 'evobot'...
remote: Enumerating objects: 2459, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 2459 (delta 31), reused 23 (delta 11), pack-reused 2408
Receiving objects: 100% (2459/2459), 1.18 MiB | 5.87 MiB/s, done.
Resolving deltas: 100% (1578/1578), done.
ubuntu@vps-693d50e9:~/discordDJ$ cd evobot/
ubuntu@vps-693d50e9:~/discordDJ/evobot$ ls
CODE_OF_CONDUCT.md  LICENSE    commands             interfaces    package-lock.json  tsconfig.json
CONTRIBUTING.md     README.md  config.json.example  locales       package.json       utils
Dockerfile          app.json   index.ts             nodemon.json  structs
ubuntu@vps-693d50e9:~/discordDJ/evobot$ vi config.json.example
ubuntu@vps-693d50e9:~/discordDJ/evobot$ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'evobot@2.7.0',
npm WARN EBADENGINE   required: { node: '>=16.11.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/builders@1.4.0',
npm WARN EBADENGINE   required: { node: '>=16.9.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/collection@1.3.0',
npm WARN EBADENGINE   required: { node: '>=16.9.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/rest@1.5.0',
npm WARN EBADENGINE   required: { node: '>=16.9.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/util@0.1.0',
npm WARN EBADENGINE   required: { node: '>=16.9.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/voice@0.16.0',
npm WARN EBADENGINE   required: { node: '>=16.9.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sapphire/async-queue@1.5.0',
npm WARN EBADENGINE   required: { node: '>=v14.0.0', npm: '>=7.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sapphire/shapeshift@3.8.1',
npm WARN EBADENGINE   required: { node: '>=v14.0.0', npm: '>=7.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sapphire/snowflake@3.4.0',
npm WARN EBADENGINE   required: { node: '>=v14.0.0', npm: '>=7.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'discord.js@14.7.1',
npm WARN EBADENGINE   required: { node: '>=16.9.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'file-type@18.2.1',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'peek-readable@5.0.0',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'play-dl@1.9.6',
npm WARN EBADENGINE   required: { node: '>=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'strtok3@7.0.0',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'token-types@5.0.1',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

added 284 packages, and audited 285 packages in 21s

34 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
ubuntu@vps-693d50e9:~/discordDJ/evobot$ npm fund
evobot@2.7.0
├── https://github.com/sponsors/sindresorhus
│   └── array-move@3.0.1, make-dir@3.1.0, strip-json-comments@3.1.1, ansi-escapes@4.3.2, type-fest@0.21.3, figures@3.2.0, ora@5.4.1, cli-spinners@2.7.0, is-unicode-supported@0.1.0, log-symbols@4.1.0, defaults@1.0.4, onetime@5.1.2
├── https://github.com/sponsors/mashpie
│   └── i18n@0.15.1
├─┬ https://opencollective.com/nodemon
│ │ └── nodemon@2.0.22
│ └── https://paulmillr.com/funding/
│     └── chokidar@3.5.3
├─┬ https://github.com/sindresorhus/file-type?sponsor=1
│ │ └── file-type@18.2.1
│ └─┬ https://github.com/sponsors/Borewit
│   │ └── readable-web-to-node-stream@3.0.2, strtok3@7.0.0, peek-readable@5.0.0, token-types@5.0.1
│   └── https://github.com/sponsors/feross
│       └── safe-buffer@5.2.1, ieee754@1.2.1, buffer@5.7.1, base64-js@1.5.1
├── https://github.com/sponsors/ljharb
│   └── minimist@1.2.7
├── https://github.com/sponsors/fb55
│   └── domelementtype@2.3.0
├── https://github.com/fb55/entities?sponsor=1
│   └── entities@2.2.0
├── https://github.com/sponsors/RubenVerborgh
│   └── follow-redirects@1.15.2
├── https://github.com/sponsors/isaacs
│   └── rimraf@3.0.2, glob@7.2.3
├── https://github.com/sponsors/jonschlinkert
│   └── picomatch@2.3.1
├─┬ https://github.com/chalk/chalk?sponsor=1
│ │ └── chalk@4.1.2
│ └── https://github.com/chalk/ansi-styles?sponsor=1
│     └── ansi-styles@4.3.0
└── https://github.com/chalk/wrap-ansi?sponsor=1
    └── wrap-ansi@7.0.0


**ubuntu@vps-693d50e9:~/discordDJ/evobot$ ls**

CODE_OF_CONDUCT.md  LICENSE    commands             interfaces    nodemon.json       structs
CONTRIBUTING.md     README.md  config.json.example  locales       package-lock.json  tsconfig.json
Dockerfile          app.json   index.ts             node_modules  package.json       utils
ubuntu@vps-693d50e9:~/discordDJ/evobot$ mv config.json.example co
commands/            config.json.example
ubuntu@vps-693d50e9:~/discordDJ/evobot$ mv config.json.example config.json
ubuntu@vps-693d50e9:~/discordDJ/evobot$ npm run start

> evobot@2.7.0 start
> ts-node index.ts

Error: Cannot find module 'node:events'
Require stack:
- /home/ubuntu/discordDJ/evobot/node_modules/discord.js/src/client/BaseClient.js
- /home/ubuntu/discordDJ/evobot/node_modules/discord.js/src/index.js
- /home/ubuntu/discordDJ/evobot/index.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/ubuntu/discordDJ/evobot/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ubuntu/discordDJ/evobot/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .js] (/home/ubuntu/discordDJ/evobot/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:863:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ubuntu/discordDJ/evobot/node_modules/discord.js/src/client/BaseClient.js',
    '/home/ubuntu/discordDJ/evobot/node_modules/discord.js/src/index.js',
    '/home/ubuntu/discordDJ/evobot/index.ts'
  ]
}
ubuntu@vps-693d50e9:~/discordDJ/evobot$ npm -v
8.5.1
ubuntu@vps-693d50e9:~/discordDJ/evobot$ node -v
v12.22.9
ubuntu@vps-693d50e9:~/discordDJ/evobot$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

```

**Environment (add if possible)**
1.npm version (8.5.1)
2.node version (v12.22.9)
3.Ubuntu version (22.04.2 LTS)

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by itsmoe15** [comment]
sorry if its not clear its my first time writing an error

**Comment by eritislami** [comment]
Please read the requirements, you must have Node 16.11 or higher

[Requirements](https://github.com/eritislami/evobot#requirements)
