### ISSUE TITLE
🐛 Age restricted content is impossible to use

### ISSUE THREAD

**Issue by rockrevenchy** [eritislami/evobot#1490]
**Describe the bug**
if you have to log on an account which is 18+ to view the video, it wont load and will throw an error

**How To Reproduce**
1. Play a song or sound from youtube which is age restricted
2. (used this as a test or exemple but many uncensored songs have the same issue)
https://www.youtube.com/watch?v=rm-9TFvvDtM
 
**Expected behavior**
To be able to play the song or perhaps being able to give a cookie from one's browser to allow the bot to bypass age restricted content

**Environment (add if possible)**
* Node.js version: 
v16.20.0

OS: Debian GNU/Linux 11 (Bullseye) aarch64
Host: Raspberry Pi 400 Rev 1.1
Kernel: 5.15.84-v8+
CPU: BCM2835 (4) @ 1.800GHz
Ram: 4GB

Log:

> Error: While getting info from url
> Sign in to confirm your age
>     at video_basic_info (/home/rockrevenchy/Apps/Music-bot/node_modules/play-dl/play-dl/YouTube/utils/extractor.ts:189:19)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Function.from (/home/rockrevenchy/Apps/Music-bot/structs/Song.ts:31:18)
>     at async Object.execute (/home/rockrevenchy/Apps/Music-bot/commands/play.ts:61:14)

**Comment by rockrevenchy** [comment]
I'm not sure if there is a way I didnt see or find to bypass that issue but I couldnt find it anywhere, could be just me tho

**Comment by rockrevenchy** [comment]
Solution found but i'll leave it here for future reference in case someone has the same issue

you need to visit this page
[https://github.com/play-dl/play-dl/tree/main/instructions#youtube-cookies](url)

long story short, get the cookie on F12 on a browser on a age restricted video, its in network in the very first request (look at the link for a proper tutorial on how to find the cookie)

create a js file at the root of the evobot folder with this code

> const play = require('play-dl');
>
>play.authorization();

run it "node newfile.js" and follow the instructions (mostly paste the cookie you got earlier)
