### ISSUE TITLE
🐛 bot won't play songs

### ISSUE THREAD

**Issue by AronF** [eritislami/evobot#1496]
**Describe the bug**
/play for most songs results in "There was an error executing that command." reply discordside, though occasionally everything works fine.
serverside error:
```
TypeError: Cannot read properties of undefined (reading 'find')
    at video_basic_info (/home/aron/evobot/node_modules/play-dl/play-dl/YouTube/utils/extractor.ts:234:159)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.from (/home/aron/evobot/structs/Song.ts:53:18)
    at async Object.execute (/home/aron/evobot/commands/play.ts:61:14)
```

**How To Reproduce**
The occurance is essentially random, though it seems certain queries result in more frequent errors. No query seems 100% reliable though.
 
**Expected behavior**
A description of what you expected to happen.
/play should play the requested song with the correct environment. It instead results in an error.

**Environment (add if possible)**
* Node.js version: v20.4.0

**Additional information & screenshots**
Add any other context or screenshots about the problem here.
![image](https://github.com/eritislami/evobot/assets/8410770/cc07dbec-7af5-4e6f-b738-6093e71c6993)

**Comment by ywanes** [comment]
#/play https://www.you  tube.com/wat  ch?v=kJQP7  kiw5Fk
TypeError: Cannot read properties of undefined (reading 'find')
    at video_basic_info (/home/evobot/node_modules/play-dl/dist/index.js:2:2210)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.from (/home/evobot/dist/structs/Song.js:23:24)
    at async Object.execute (/home/evobot/dist/commands/play.js:54:20)

**Comment by eritislami** [comment]
Run `npm ci` to get the latest `play-dl` package version
