### ISSUE TITLE
Error: Status code: 429

### ISSUE THREAD

**Issue by bobo4545** [eritislami/evobot#150]
Error: Status code: 429
    at ClientRequest.<anonymous> (/rbd/pnpm-volume/531ce59f-20ca-4d2a-9ad0-e7b9dbf69f8d/node_modules/.registry.npmjs.org/miniget/1.7.2/node_modules/miniget/dist/index.js:141:31)
    at Object.onceWrapper (events.js:284:20)
    at ClientRequest.emit (events.js:196:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:452:22)
    at TLSSocket.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at TLSSocket.Readable.push (_stream_readable.js:226:10)

**Comment by eritislami** [comment]
It's http error 429 (too many requests), nothing i can do about it

https://httpstatuses.com/429
