### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by tjc15b** [eritislami/evobot#1514]
**Describe the bug**
Bot eventually breaks and won't play any songs "application does not respond"

**How To Reproduce**
Not sure. Have the bot running in my server 24/7 and eventually it breaks.
 
**Expected behavior**
Song plays.

**Environment (add if possible)**
* Node.js version: v20.7.0

**Additional information & screenshots**
```
DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/home/taylor/evobot/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/home/taylor/evobot/node_modules/@discordjs/rest/src/lib/handlers/BurstHandler.ts:136:20)
    at async _REST.request (/home/taylor/evobot/node_modules/@discordjs/rest/src/lib/REST.ts:211:20)
    at async ChatInputCommandInteraction.reply (/home/taylor/evobot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5) {
  requestBody: { files: [], json: { type: 4, data: [Object] } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1162568823300423711/aW50ZXJhY3Rpb246MTE2MjU2ODgyMzMwMDQyMzcxMTpJSDJRY05Xb1d2aXA1ZkdlVTVyMkozaVUwRGN3aFZmQ0VPQThhWFJmM1VzUVZIc0s2NE5xemgwNVhGd1lSaFJyaUowODVvTEhZUnQ5NGVrOVlZOHY4dnJNZUEyNkdJUGNudlMwV2VYbUFXeGdic1ZUSWxVdDJvUEVpUjNhOVZiZg/callback'
}
Error: getaddrinfo EAI_AGAIN www.youtube.com
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'www.youtube.com'
}

```

**Comment by TeamLipra** [comment]
having the same issue.

**Comment by eritislami** [comment]
Closing due to out of date

**Comment by Xeonis** [comment]
Hey guys, got it again

Ubuntu 22.04.3
Node  v21.6.1
runing from pm2

Before this, everything worked well, but literally a few days later the music stopped playing and the bot went into reboot
try to fix:
1) Did a clean install from gitHub
2) Reset and installed a new key


```log
1|evobot  | Bot ready!
1|evobot  | (node:10613) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
1|evobot  | (Use `node --trace-deprecation ...` to show where the warning was created)
1|evobot  | /scr/evobot/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148
1|evobot  |                     throw new DiscordAPIError(data, 'code' in data ? data.code : data.error, status, method, url, requestData);
1|evobot  |          ^
1|evobot  | DiscordAPIError[10062]: Unknown interaction
1|evobot  |     at handleErrors (/scr/evobot/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)
1|evobot  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
1|evobot  |     at async BurstHandler.runRequest (/scr/evobot/node_modules/@discordjs/rest/src/lib/handlers/BurstHandler.ts:144:20)
1|evobot  |     at async _REST.request (/scr/evobot/node_modules/@discordjs/rest/src/lib/REST.ts:210:20)
1|evobot  |     at async ChatInputCommandInteraction.reply (/scr/evobot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:114:5)
1|evobot  |     at async Object.execute (/scr/evobot/commands/play.ts:44:10) {
1|evobot  |   requestBody: { files: [], json: { type: 4, data: [Object] } },
1|evobot  |   rawError: { message: 'Unknown interaction', code: 10062 },
1|evobot  |   code: 10062,
1|evobot  |   status: 404,
1|evobot  |   method: 'POST',
1|evobot  |   url: 'https://discord.com/api/v10/interactions/PrivateDATAHERE/callback'
1|evobot  | }
1|evobot  | > evobot@2.9.0 start
1|evobot  | > ts-node index.ts
```
