### ISSUE TITLE
🐛 Consider using try/catch instead of simply do ``return reply....`` 

### ISSUE THREAD

**Issue by tchereau** [eritislami/evobot#1529]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1. Miss setting up a role or having a dangerous login bug
2. let the bot crash because there is no try/crash to deal with exceptions.
 
**Expected behavior**
No more to say, juste use try/catch to deal with exceptions.

**Additional information & screenshots**
```bash
miousic ready!
/home/evobot/node_modules/@discordjs/rest/dist/index.js:687
      throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
            ^
DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/home/evobot/node_modules/@discordjs/rest/dist/index.js:687:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BurstHandler.runRequest (/home/evobot/node_modules/@discordjs/rest/dist/index.js:786:23)
    at async _REST.request (/home/evobot/node_modules/@discordjs/rest/dist/index.js:1218:22)
    at async ChatInputCommandInteraction.reply (/home/evobot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
    at async Object.execute (/home/evobot/dist/commands/play.js:46:13) {
  requestBody: {
    files: [],
    json: {
      type: 4,
      data: {
        content: '⏳ Loading...',
        tts: false,
        nonce: undefined,
        embeds: undefined,
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: undefined,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined,
        thread_name: undefined
      }
    }
  },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/youRealyWantMyToken/dontYou?/callback'
}
> evobot@2.8.1 prod
> npm run build && node ./dist/index.js
> evobot@2.8.1 build
> tsc --build
```

**Comment by tchereau** [comment]
for example
```typescript
   import { ChatInputCommandInteraction, EmbedBuilder, SlashCommandBuilder } from "discord.js";
import { i18n } from "../utils/i18n";
// @ts-ignore
import lyricsFinder from "lyrics-finder";
import { bot } from "../index";

export default {
  data: new SlashCommandBuilder().setName("lyrics").setDescription(i18n.__("lyrics.description")),
  async execute(interaction: ChatInputCommandInteraction) {
    const queue = bot.queues.get(interaction.guild!.id);

    if (!queue || !queue.songs.length) return interaction.reply(i18n.__("lyrics.errorNotQueue")).catch(console.error);

    await interaction.reply("⏳ Loading...").catch(console.error);

    let lyrics = null;
    const title = queue.songs[0].title;

    try {
      lyrics = await lyricsFinder(queue.songs[0].title, "");
      if (!lyrics) lyrics = i18n.__mf("lyrics.lyricsNotFound", { title: title });
    } catch (error) {
      lyrics = i18n.__mf("lyrics.lyricsNotFound", { title: title });
    }

    let lyricsEmbed = new EmbedBuilder()
      .setTitle(i18n.__mf("lyrics.embedTitle", { title: title }))
      .setDescription(lyrics.length >= 4096 ? `${lyrics.substr(0, 4093)}...` : lyrics)
      .setColor("#F8AA2A")
      .setTimestamp();

    return interaction.editReply({ content: "", embeds: [lyricsEmbed] }).catch(console.error);
  }
};
```

a try/catch is also needed for 
```typescript
  await interaction.reply("⏳ Loading...").catch(console.error);
 ```

try/catch should be everywhere
a world of try/catch
try/catch try/catch try/catch try/catch (sorry)

**Comment by eritislami** [comment]
Handled in latest release
