### ISSUE TITLE
🐛 Sign in to confirm you’re not a bot

### ISSUE THREAD

**Issue by kibubek** [eritislami/evobot#1638]
**Describe the bug**
play-dl asking you to sign in to confirm you're not a bot (It is a bot)

**How To Reproduce**
1. Run the latest version
2. Play a song
 
**Expected behavior**
Not ask me to verify im not a bot.

**Environment (add if possible)**
* Node.js version: v18.20.3

**Additional information & screenshots**
Obsidian Drum ready!
Error: While getting info from url
Sign in to confirm you’re not a bot
    at video_basic_info (/home/container/node_modules/play-dl/play-dl/YouTube/utils/extractor.ts:191:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.from (/home/container/structs/Song.ts:31:18)
    at async Object.execute (/home/container/commands/play.ts:56:14)

**Comment by DFanso** [comment]
same issue

**Comment by deadsilense** [comment]
Bump

**Comment by kibubek** [comment]
I found out the cause. 
Youtube has been ip banning adresses and it's not like this will go away. I recommend using other bots using lavalink as that has not been patched and the measures lavalink can take to mitigate the banning.
