### ISSUE TITLE
Bug: Bot Won't Activate

### ISSUE THREAD

**Issue by Pierzety** [eritislami/evobot#186]
I followed everything and when I did ran  index.js in my terminal and I couldn't do anything besides get this result..

/home/nathan/node_modules/discord.js/src/client/Client.js:41
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/nathan/node_modules/discord.js/src/index.js:8:11)

**Comment by eritislami** [comment]
You need node.js v12 or newer

**Comment by Pierzety** [comment]
fixed
