### ISSUE TITLE
Bug: it is impossible to make the music work

### ISSUE THREAD

**Issue by RyzenK8** [eritislami/evobot#196]
**Describe the bug**
A description of what the bug is.
container@pterodactyl~ Server marked as starting...
:/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi && /usr/local/bin/npm install --production && /usr/local/bin/node /home/container/${BOT_JS_FILE}
audited 131 packages in 2.867s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Lokia ready!
`info.length_seconds` will be removed in a near future release, use `info.videoDetails.lengthSeconds` instead.
(node:24) UnhandledPromiseRejectionWarning: Error: Error: Cannot find module '/home/container/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.28/opus.node'
Require stack:
- /home/container/node_modules/@discordjs/opus/lib/index.js
- /home/container/node_modules/prism-media/src/util/loader.js
- /home/container/node_modules/prism-media/src/opus/Opus.js
- /home/container/node_modules/prism-media/src/opus/index.js
- /home/container/node_modules/prism-media/src/index.js
- /home/container/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/container/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/container/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/container/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/container/node_modules/discord.js/src/client/Client.js
- /home/container/node_modules/discord.js/src/index.js
- /home/container/index.js
Error: Cannot find module 'node-opus'
Require stack:
- /home/container/node_modules/prism-media/src/util/loader.js
- /home/container/node_modules/prism-media/src/opus/Opus.js
- /home/container/node_modules/prism-media/src/opus/index.js
- /home/container/node_modules/prism-media/src/index.js
- /home/container/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/container/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/container/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/container/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/container/node_modules/discord.js/src/client/Client.js
- /home/container/node_modules/discord.js/src/index.js
- /home/container/index.js
Error: Cannot find module 'opusscript'
Require stack:
- /home/container/node_modules/prism-media/src/util/loader.js
- /home/container/node_modules/prism-media/src/opus/Opus.js
- /home/container/node_modules/prism-media/src/opus/index.js
- /home/container/node_modules/prism-media/src/index.js
- /home/container/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/container/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/container/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/container/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/container/node_modules/discord.js/src/client/Client.js
- /home/container/node_modules/discord.js/src/index.js
- /home/container/index.js
    at Object.loader [as require] (/home/container/node_modules/prism-media/src/util/loader.js:12:9)
    at loadOpus (/home/container/node_modules/prism-media/src/opus/Opus.js:17:17)
    at new OpusStream (/home/container/node_modules/prism-media/src/opus/Opus.js:46:10)
    at new Decoder (/home/container/node_modules/prism-media/src/opus/Opus.js:169:1)
    at AudioPlayer.playOpusStream (/home/container/node_modules/discord.js/src/client/voice/player/BasePlayer.js:73:23)
    at VoiceConnection.play (/home/container/node_modules/discord.js/src/client/voice/util/PlayInterface.js:75:28)
    at play (/home/container/include/play.js:51:8)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**How To Reproduce**
1 I press the start button
2 $play https://www.youtube.com/watch?v=66765
3. it is impossible to make the music work
 
**Expected behavior**
A description of what you expected to happen.
The moment I start the server it works well but the moment it starts the music it makes mistakes

**Environment (add if possible)**
* Node.js version: 12.18.4 LTS

**Additional information & screenshots**
https://imgur.com/a/eEzlYxA

**Comment by RyzenK8** [comment]
I found a fix for vps or nodejs server
{
  "name": "evobot",
  "version": "0.7.0",
  "description": "Discord music bot built with discord.js",
  "main": "index.js",
  "author": "Erit Islami <eritislami@gmail.com>",
  "private": true,
  "homepage": "https://github.com/eritislami/evobot",
  "repository": "github:eritislami/evobot",
  "bugs": "https://github.com/eritislami/evobot/issues",
  "engines": {
    "node": ">=12.0.0"
  },
  "dependencies": {
    "@discordjs/opus": "^0.3.2",
    "discord.js": "^12.0.1",
    "ffmpeg-static": "^4.2.3",
    "lyrics-finder": "^21.0.5",
    "simple-youtube-api": "^5.1.1",
    "soundcloud-downloader": "^0.1.6",
    "string-progressbar": "^1.0.1",
    "ytdl-core": "^3.1.0",
    "ytdl-core-discord": "^1.2.1",
    "opusscript": "^0.0.7",
    "node-opus": "^0.3.3"
  },
  "scripts": {
    "start": "node index.js"
  }
}
