### ISSUE TITLE
Cannot find module 'lyrics-finder'

### ISSUE THREAD

**Issue by Pierzety** [eritislami/evobot#207]
:~/Desktop/evobot-master$ node index.js
internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module 'lyrics-finder'
Require stack:
- /home/nathan/Desktop/evobot-master/commands/lyrics.js
- /home/nathan/Desktop/evobot-master/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/nathan/Desktop/evobot-master/commands/lyrics.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/nathan/Desktop/evobot-master/commands/lyrics.js',
    '/home/nathan/Desktop/evobot-master/index.js'
  ]
}

**Comment by Raphilia** [comment]
Have you installed the dependency?

`npm install lyrics-finder` or just `npm install`
