### ISSUE TITLE
SyntaxError: Unexpected token.

### ISSUE THREAD

**Issue by ProgramFreakHD** [eritislami/evobot#21]
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/bots/evobot/node_modules/discord.js/src/index.js:8:11)

This got to be a joke. If i delete your package.json and replace it with my own i get another garbage error: (node:26823) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `channel` of 'undefined' or 'nu                                                                                                                        ll'.
    at Object.execute (/root/bots/evobot/commands/play.js:11:40)
    at Client.client.on (/root/bots/evobot/index.js:48:36)

**Comment by eritislami** [comment]
Unexpected token means your file encoding is not supported by node.js or you have copy pasted some non-utf8 character into the script, set encoding to UTF-8 on your code editor or try cloning a fresh copy of the repository

**Comment by ProgramFreakHD** [comment]
Ok so i cloned a fresh copy of the repository, made a config.json file and filled out the necessary credential, uploaded it to my ubuntu server, installed node_modules by typing ```npm install```, tried to run the bot with node index.js and it's still the same error, "Unexpected token {".
![putty_TWvZ5Fsjw0](https://user-images.githubusercontent.com/33644886/81062294-fc485b00-8ed5-11ea-807f-e086e5459443.png)

**Comment by eritislami** [comment]
Perhaps you are using an old version of node js?

**Comment by eritislami** [comment]
Closing for inactivity
