### ISSUE TITLE
Bug: Error: Error: Could not find player config

### ISSUE THREAD

**Issue by alide123321** [eritislami/evobot#215]
**Describe the bug**
Music queue ended.
some songs give me this error

Error: Could not find player config
    at exports.getBasicInfo (/home/runner/discordbot/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:59:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.<computed> [as getBasicInfo] (/home/runner/discordbot/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:296:18)
    at async exports.getFullInfo (/home/runner/discordbot/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:187:14)
    at async Object.exports.<computed> [as getFullInfo] (/home/runner/discordbot/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:296:18)

**How To Reproduce**
1. play this video https://youtu.be/21CScnMa4nU
 
**Expected behavior**
should play the meme

**Environment (add if possible)**
* Node.js version: v12.18.3

**Comment by fdciabdul** [comment]
> **Describe the bug**
> Music queue ended.
> some songs give me this error
> 
> Error: Could not find player config
> at exports.getBasicInfo (/home/runner/discordbot/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:59:13)
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> at async Object.exports. [as getBasicInfo] (/home/runner/discordbot/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:296:18)
> at async exports.getFullInfo (/home/runner/discordbot/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:187:14)
> at async Object.exports. [as getFullInfo] (/home/runner/discordbot/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:296:18)
> 
> **How To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. play this video https://youtu.be/21CScnMa4nU
> 
> **Expected behavior**
> should play the meme
> 
> **Environment (add if possible)**
> 
> * Node.js version: v12.18.3

ytdl cannot play videos with age resticted :)

**Comment by alide123321** [comment]
> ytdl cannot play videos with age resticted :)

is there away around that?
