### ISSUE TITLE
Bug: error code: 429 if i play music with link youtube and No video was found with a matching title if i play with song title

### ISSUE THREAD

**Issue by rizkijn123** [eritislami/evobot#231]

**Comment by Anogh297** [comment]
Same problem

**Comment by Anogh297** [comment]
Error: Status code: 429
    at ClientRequest.<anonymous> (/home/container/node_modules/ytdl-core/node_modules/miniget/dist/index.js:150:31)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:640:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at TLSSocket.Readable.push (_stream_readable.js:218:10)

**Comment by 6102yk** [comment]
same problem

**Comment by 6102yk** [comment]
2020-10-10T16:18:47.149272+00:00 app[Worker.1]: Error: Status code: 429
2020-10-10T16:18:47.149284+00:00 app[Worker.1]:     at ClientRequest.<anonymous> (/app/node_modules/ytdl-core/node_modules/miniget/dist/index.js:150:31)
2020-10-10T16:18:47.149285+00:00 app[Worker.1]:     at Object.onceWrapper (events.js:421:26)
2020-10-10T16:18:47.149285+00:00 app[Worker.1]:     at ClientRequest.emit (events.js:314:20)
2020-10-10T16:18:47.149286+00:00 app[Worker.1]:     at HTTPParser.parserOnIncomingClient (_http_client.js:640:27)
2020-10-10T16:18:47.149287+00:00 app[Worker.1]:     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
2020-10-10T16:18:47.149288+00:00 app[Worker.1]:     at TLSSocket.socketOnData (_http_client.js:509:22)
2020-10-10T16:18:47.149288+00:00 app[Worker.1]:     at TLSSocket.emit (events.js:314:20)
2020-10-10T16:18:47.149289+00:00 app[Worker.1]:     at addChunk (_stream_readable.js:307:12)
2020-10-10T16:18:47.149289+00:00 app[Worker.1]:     at readableAddChunk (_stream_readable.js:282:9)
2020-10-10T16:18:47.149290+00:00 app[Worker.1]:     at TLSSocket.Readable.push (_stream_readable.js:221:10)

**Comment by L0SER8228** [comment]
I'm also getting the same problem from some days. Before it's working fine.

**Comment by eritislami** [comment]
Please check google, error 429 is related to api key
