### ISSUE TITLE
Error: FFmpeg/avconv not found!

### ISSUE THREAD

**Issue by ZeskOficial** [eritislami/evobot#246]
**Describe the bug**
`Error: FFmpeg/avconv not found!`

**How To Reproduce**
`Some videos give me this error while im trying to play it:`

```
at Function.getInfo (C:\Users\perri\Desktop\evobot-0.7.0\node_modules\prism-media\src\core\FFmpeg.js:130:11)
    at Function.create (C:\Users\perri\Desktop\evobot-0.7.0\node_modules\prism-media\src\core\FFmpeg.js:143:38)
    at new FFmpeg (C:\Users\perri\Desktop\evobot-0.7.0\node_modules\prism-media\src\core\FFmpeg.js:44:27)
    at download (C:\Users\perri\Desktop\evobot-0.7.0\node_modules\ytdl-core-discord\index.js:38:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async play (C:\Users\perri\Desktop\evobot-0.7.0\include\play.js:20:18)
```

**Environment (add if possible)**
* Node.js version: `12.19.0`

**Additional information & screenshots**
`All is the described previusly.`

**Comment by KeepSOBP** [comment]
Install ffmpeg :>

**Comment by ZeskOficial** [comment]
> Install ffmpeg :>

as i said is in some songs, I can play music bro

**Comment by Velosofy** [comment]
> > Install ffmpeg :>
> 
> as i said is in some songs, I can play music bro

try to

npm install ffmpeg-static
