### ISSUE TITLE
Add Shuffle Command

### ISSUE THREAD

**Issue by Wers7y** [eritislami/evobot#28]
Can you add shuffle command to this wonderful bot?

**Comment by Atom-Dragon** [comment]
> Can you add shuffle command to this wonderful bot?

Hey bud i made a shuffle command for the bot u can find the codes here hope it helps :)
just rename the shuffle.txt with shuffle.js and put it in your commands folder 

[shuffle.txt](https://github.com/eritislami/evobot/files/4641469/shuffle.txt)

**Comment by Wers7y** [comment]
It returns me an error(

**Comment by Wers7y** [comment]
> > Can you add shuffle command to this wonderful bot?
> 
> Hey bud i made a shuffle command for the bot u can find the codes here hope it helps :)
> just rename the shuffle.txt with shuffle.js and put it in your commands folder
> 
> [shuffle.txt](https://github.com/eritislami/evobot/files/4641469/shuffle.txt)

It returns me an error(

**Comment by Atom-Dragon** [comment]
> > > Can you add shuffle command to this wonderful bot?
> > 
> > 
> > Hey bud i made a shuffle command for the bot u can find the codes here hope it helps :)
> > just rename the shuffle.txt with shuffle.js and put it in your commands folder
> > [shuffle.txt](https://github.com/eritislami/evobot/files/4641469/shuffle.txt)
> 
> It reacts, but returns me an error(

Can u people show what the error is

**Comment by Wers7y** [comment]
> > > > Can you add shuffle command to this wonderful bot?
> > > 
> > > 
> > > Hey bud i made a shuffle command for the bot u can find the codes here hope it helps :)
> > > just rename the shuffle.txt with shuffle.js and put it in your commands folder
> > > [shuffle.txt](https://github.com/eritislami/evobot/files/4641469/shuffle.txt)
> > 
> > 
> > It reacts, but returns me an error(
> 
> Can u please show what the error is 😁
It says "There was an error executing that command."

**Comment by VirusLauncher** [comment]
Tested via Glitch, this is the set of error codes:

Error: Status code: 500
    at ClientRequest.<anonymous> (/rbd/pnpm-volume/84f277f9-dfff-488e-8892-8a11e781b4dc/node_modules/.registry.npmjs.org/miniget/1.7.0/node_modules/miniget/dist/index.js:128:27)
    at Object.onceWrapper (events.js:284:20)
    at ClientRequest.emit (events.js:196:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:452:22)
    at TLSSocket.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at TLSSocket.Readable.push (_stream_readable.js:226:10)
(node:2614) UnhandledPromiseRejectionWarning: Error [VOICE_PLAY_INTERFACE_BAD_TYPE]: Unknown stream type
    at VoiceConnection.play (/rbd/pnpm-volume/84f277f9-dfff-488e-8892-8a11e781b4dc/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/client/voice/util/PlayInterface.js:84:11)
at play (/app/include/play.js:31:8)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:2614) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2614) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Atom-Dragon** [comment]
Oof my bad i forget to mention the serverQueue lol 
it should work now :) 
[shuffle.txt](https://github.com/eritislami/evobot/files/4653049/shuffle.txt)

**Comment by Wers7y** [comment]
> Oof my bad i forget to mention the serverQueue lol
> it should work now :)
> [shuffle.txt](https://github.com/eritislami/evobot/files/4653049/shuffle.txt)
> @Wers7y
> @VirusLauncher
> and @Wers7y if it works plz close the issue

Now it sends me this error:
null: TypeError: Cannot read property 'id' of null
message: "Cannot read property 'id' of null"
stack: "TypeError: Cannot read property 'id' of null
    at Object.execute (c:\Users\User\Desktop\bot2\msbot\commands\shuffle.js:25:40)
    at Client.<anonymous> (c:\Users\User\Desktop\bot2\msbot\index.js:42:36)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (c:\Users\User\Desktop\bot2\msbot\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (c:\Users\User\Desktop\bot2\msbot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (c:\Users\User\Desktop\bot2\msbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (c:\Users\User\Desktop\bot2\msbot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (c:\Users\User\Desktop\bot2\msbot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (c:\Users\User\Desktop\bot2\msbot\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)"
__proto__: Error {constructor: , name: "TypeError", message: ""}

**Comment by Atom-Dragon** [comment]
Oof Dam this is annoying alright try to remove this line `(message.guild.me.voice.channel.id != message.member.voice.channel.id)
    return message.reply("You must be in the same channel as me")` and see if it works

**Comment by Wers7y** [comment]
> Oof Dam this is annoying alright try to remove this line `(message.guild.me.voice.channel.id != message.member.voice.channel.id) return message.reply("You must be in the same channel as me")` and see if it works

Everything works perfectly! Thanks! Closing the issue.

**Comment by VirusLauncher** [comment]
@Atom-Dragon Thanks it works now 👍
