### ISSUE TITLE
Error at creating the embeds

### ISSUE THREAD

**Issue by Tobikisss** [eritislami/evobot#290]
Error when doing (prefix)help:

TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/dcbots/evobot/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.addFields (/home/dcbots/evobot/node_modules/discord.js/src/structures/MessageEmbed.js:266:42)
    at MessageEmbed.addField (/home/dcbots/evobot/node_modules/discord.js/src/structures/MessageEmbed.js:257:17)
    at commands.forEach (/home/dcbots/evobot/commands/help.js:16:17)
    at Array.forEach (<anonymous>)
    at Object.execute (/home/dcbots/evobot/commands/help.js:15:14)
    at Client.client.on (/home/dcbots/evobot/index.js:87:13)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (/home/dcbots/evobot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/dcbots/evobot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)

Error when doing (prefix)search trap mix:

TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/dcbots/evobot/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.addFields (/home/dcbots/evobot/node_modules/discord.js/src/structures/MessageEmbed.js:266:42)
    at MessageEmbed.addField (/home/dcbots/evobot/node_modules/discord.js/src/structures/MessageEmbed.js:257:17)
    at results.map (/home/dcbots/evobot/commands/search.js:33:50)
    at Array.map (<anonymous>)
    at Object.execute (/home/dcbots/evobot/commands/search.js:33:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

problem is generating the embeds, but i dont know how to deal with it.

**Comment by eritislami** [comment]
Problem is your node.js version is less than 12.0.0, https://nodejs.org/en/download/
