### ISSUE TITLE
add to Uptime command

### ISSUE THREAD

**Issue by sam920829** [eritislami/evobot#308]

**Comment by wolf-yuan-6115** [comment]
Uptime command is very simple ._.

You can try this:
Add a file to `command` folder and name it `uptime.js`
Add these code to `uptime.js`
```js
module.export{
  name: "uptime",
  description: "Get bot's uptime",
  execute (message) {
    const milli = message.client.uptime;
    let minutes = Math.floor(milli / 60000);
    let hours = Math.round(minutes / 60);
    let days = Math.round(hours / 24);

    return message.channel.send (days && {days: days}) || (hours && {hours: hours}) || {minutes: minutes});
}
```

**Comment by sam920829** [comment]
> 正常運行時間命令非常簡單。
> 
> 您可以嘗試以下操作：
> 將文件添加到`command`文件夾並為其命名`uptime.js`
> 將這些代碼添加到`uptime.js`
> 
> ```js
> 模塊。出口{
>   名稱：“正常運行時間” ，
>   描述：“獲取bot的正常運行時間” ，
>   執行 （消息） { 
>     const  milli  =  message 。客戶。正常運行時間; 
>     讓 分鐘 = 數學。地板（毫米/ 60000 ）; 
>     讓 小時 = 數學。輪（分鐘/ 60 ）; 
>     讓 天 = 數學。圓（小時/ 24 ）; 
> 
>     返回 消息。渠道。發送 （天 &&  {天：天} ） ||  （小時 &&  {小時：小時} ） ||  {分鐘：分鐘} ）; 
> }
> ```

C:\Users\user\Downloads\evobot-master\evobot-master>node index.js
C:\Users\user\Downloads\evobot-master\evobot-master\commands\uptime.js:1
module.export{
             ^

SyntaxError: Unexpected token '{'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\user\Downloads\evobot-master\evobot-master\index.js:43:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**Comment by sam920829** [comment]
C:\Users\user\Downloads\evobot-master\evobot-master>node index.js
C:\Users\user\Downloads\evobot-master\evobot-master\commands\uptime.js:1
module.export{
             ^

SyntaxError: Unexpected token '{'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\user\Downloads\evobot-master\evobot-master\index.js:43:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

C:\Users\user\Downloads\evobot-master\evobot-master>pause

**Comment by wolf-yuan-6115** [comment]
> C:\Users\user\Downloads\evobot-master\evobot-master>node index.js
> C:\Users\user\Downloads\evobot-master\evobot-master\commands\uptime.js:1
> module.export{
>              ^
> 
> SyntaxError: Unexpected token '{'
>     at wrapSafe (internal/modules/cjs/loader.js:979:16)
>     at Module._compile (internal/modules/cjs/loader.js:1027:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (C:\Users\user\Downloads\evobot-master\evobot-master\index.js:43:19)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> 
> C:\Users\user\Downloads\evobot-master\evobot-master>pause

Hi , sorry for the error , I already fix that error, please try again!

**Comment by sam920829** [comment]
C:\Users\user\Downloads\evobot-master\evobot-master>node index.js
C:\Users\user\Downloads\evobot-master\evobot-master\commands\uptime.js:1
module​.​exports​ ​=​ ​{​


SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\user\Downloads\evobot-master\evobot-master\index.js:43:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**Comment by wolf-yuan-6115** [comment]
@sam920829 
https://github.com/eritislami/evobot/issues/308#issuecomment-723557630

**Comment by sam920829** [comment]
C:\Users\user\Downloads\evobot-master\evobot-master>node index.js
C:\Users\user\Downloads\evobot-master\evobot-master\commands\uptime.js:10
    return message.channel.send (days && {days: days}) || (hours && {hours: hours}) || {minutes: minutes});
                                                                                                         ^

SyntaxError: Unexpected token ')'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\user\Downloads\evobot-master\evobot-master\index.js:43:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

C:\Users\user\Downloads\evobot-master\evobot-master>pause

**Comment by wolf-yuan-6115** [comment]
Eww...
@eritislami Can you help me ._.

**Comment by eritislami** [comment]
**feat: add uptime command (f583e354bad8b63a66f8a2bb4539c9d1795dc198)**

```js
module.exports = {
  name: "uptime",
  aliases: ["u"],
  description: "Check the uptime",
  execute(message) {
    let seconds = Math.floor(message.client.uptime / 1000);
    let minutes = Math.floor(seconds / 60);
    let hours = Math.floor(minutes / 60);
    let days = Math.floor(hours / 24);

    seconds %= 60;
    minutes %= 60;
    hours %= 24;

    return message
      .reply(`Uptime: \`${days} day(s),${hours} hours, ${minutes} minutes, ${seconds} seconds\``)
      .catch(console.error);
  }
};

```
