### ISSUE TITLE
bot is not starting how to fix it

### ISSUE THREAD

**Issue by sanikava** [eritislami/evobot#31]
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'node-fetch'
Require stack:
- e:\discord bot\evobot-master\node_modules\discord.js\src\util\Util.js
- e:\discord bot\evobot-master\node_modules\discord.js\src\index.js
- e:\discord bot\evobot-master\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (e:\discord bot\evobot-master\node_modules\discord.js\src\util\Util.js:4:15)
    at

**Comment by eritislami** [comment]
Could be a few reasons, first you can try deleting node_modules folder and run npm install in the directory and then try again

**Comment by DirectX-Luck** [comment]
You just have to open the terminal and Install the NPM Packages using ``npm i <ModuleName>``

EG:
npm i discord.js
npm i ytdl-core

**Comment by eritislami** [comment]
Closing for inactivity
