### ISSUE TITLE
Error: Could not find player config

### ISSUE THREAD

**Issue by ritam110204** [eritislami/evobot#319]
**Describe the bug**
Error: Could not find player config
    at exports.getBasicInfo (/home/runner/RILP-MUSIC-BOT/node_modules/ytdl-core/lib/info.js:90:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Map.getOrSet (/home/runner/RILP-MUSIC-BOT/node_modules/ytdl-core/lib/cache.js:24:19)
    at async exports.getInfo (/home/runner/RILP-MUSIC-BOT/node_modules/ytdl-core/lib/info.js:215:14)
    at async Map.getOrSet (/home/runner/RILP-MUSIC-BOT/node_modules/ytdl-core/lib/cache.js:24:19)
    at async Object.execute (/home/runner/RILP-MUSIC-BOT/commands/play.js:93:20)

**How To Reproduce**
1. When I am playing any song the error is coming. I tried to play the song Happier, Faded none of them played.
 
**Expected behavior**
Whenever I am trying to play any song.

**Environment (add if possible)**
* Node.js version: 12.8.3

**Comment by wolf-yuan-6115** [comment]
Hi @ritam110204 , this error will appear **randomly** (I think) , you can try again.

**Comment by hadiabbasjafry** [comment]
having this error myself what to do here

**Comment by wolf-yuan-6115** [comment]
I changed `discord-ytdl-core` to `ytdl-core` because `discord-ytdl-core` can't play music, but @eritislami didn't merge my pull request because bot is working better with `discord-ytdl-core`

**Comment by BlazeDexX** [comment]
> I changed `discord-ytdl-core` to `ytdl-core` because `discord-ytdl-core` can't play music, but @eritislami didn't merge my pull request because bot is working better with `discord-ytdl-core`

my bot cannot play some song with module ytdl-core like this song https://www.youtube.com/watch?v=s4lgO3Ueq70

**Comment by eritislami** [comment]
If you can, please try again with latest commit / packages and let me know if it's ok
