### ISSUE TITLE
Bug: Soundcloud NPM Package Causing Failure

### ISSUE THREAD

**Issue by dylanjames-js** [eritislami/evobot#327]
**Describe the bug**
The NPM package for the soundcloud downloader is all the sudden now throwing this error after I switched to a different vps. The npm and node version is the same, the OS is the same, nothing's really changed at all except the vps host itself.

**How To Reproduce**
1. `node .`
 
**Expected behavior**
The bot to start up normally.

**Environment (add if possible)**
* Node.js version: 14.15.0

**Additional information & screenshots**
```TypeError: Cannot read property 'toLowerCase' of undefined
    at new SCDL (/root/tritan-bot/bot/node_modules/soundcloud-downloader/dist/index.js:92:56)
    at Object.<anonymous> (/root/tritan-bot/bot/node_modules/soundcloud-downloader/dist/index.js:369:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/tritan-bot/bot/node_modules/soundcloud-downloader/index.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)```

**Comment by dylanjames-js** [comment]
So sorry, removing and reinstalling fixed the issue.
