### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by hadiabbasjafry** [eritislami/evobot#347]
/home/container/commands/help.js:26
  }
   

SyntaxError: Unexpected end of input
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/container/index.js:42:19)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)

having this error here updated all the files something is wrong

**Comment by eritislami** [comment]
Did you make code changes? i don't see any other reason to get this error

**Comment by hadiabbasjafry** [comment]
Did , the new updates added a new feature "inviteme.js" everything was working fine until something related to ytdl not playing music started and now i am getting this error

**Comment by eritislami** [comment]
This is an error from your code
