### ISSUE TITLE
Bug: youtube playlist error

### ISSUE THREAD

**Issue by DEV-TGX** [eritislami/evobot#395]
Error: Error parsing info: Unable to retrieve video metadata
    at getWatchPage (/home/runner/make-one/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:75:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async exports.getBasicInfo (/home/runner/make-one/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:84:22)
    at async Map.getOrSet (/home/runner/make-one/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/cache.js:24:19)
    at async exports.getInfo (/home/runner/make-one/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:226:14)
    at async Map.getOrSet (/home/runner/make-one/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/cache.js:24:19)
    at async download (/home/runner/make-one/node_modules/ytdl-core-discord/index.js:26:15)
    at async Object.play (/home/runner/make-one/include/play.js:25:18)

**Comment by eritislami** [comment]
Check other issues with this error.
