### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by erodev2004** [eritislami/evobot#396]
**Describe the bug**
When im trying to play music the bot gives error ``Error: Error parsing info: Unable to retrieve video metadata``

**How To Reproduce**
1. Launch the bot
2. Play some music
 
**Expected behavior**
Music should play

**Environment (add if possible)**
* Node.js version:  v12.18.4

**Additional information & screenshots**
error in terminal```Error: Error parsing info: Unable to retrieve video metadata
    at getWatchPage (/root/music/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:75:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async exports.getBasicInfo (/root/music/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:84:22)
    at async Map.getOrSet (/root/music/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/cache.js:24:19)
    at async exports.getInfo (/root/music/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:226:14)
    at async Map.getOrSet (/root/music/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/cache.js:24:19)
    at async download (/root/music/node_modules/ytdl-core-discord/index.js:26:15)
    at async play (/root/music/include/play.js:36:18)```

**Comment by y0rune** [comment]
I have the same issue on the latest version of evobot. I use node v10.19.0.

```bash
b571@b571:~/evobot$ node index.js
音楽ボット ready!
Error: Error parsing info: Unable to retrieve video metadata
    at getWatchPage (/home/b571/evobot/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:75:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Error parsing info: Unable to retrieve video metadata
    at getWatchPage (/home/b571/evobot/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:75:13)
    at process._tickCallback (internal/process/next_tick.js:68:7
```

**Comment by eritislami** [comment]
It's ytdl nothing i can do about it.
