### ISSUE TITLE
Bug: scdl.isValidUrl is not a function

### ISSUE THREAD

**Issue by YellowBanana508** [eritislami/evobot#414]
**Describe the bug**
A description of what the bug is.
Was trying to host this thing on heroku! But it didnt work as expected......
2020-12-02T13:13:26.770306+00:00 app[worker.1]: AfroJack ready!
2020-12-02T13:13:43.104139+00:00 app[worker.1]: /app/commands/play.js:42
2020-12-02T13:13:43.104171+00:00 app[worker.1]:     } else if (scdl.isValidUrl(url) && url.includes("/sets/")) {
2020-12-02T13:13:43.104172+00:00 app[worker.1]:                     ^
2020-12-02T13:13:43.104173+00:00 app[worker.1]: 
2020-12-02T13:13:43.104173+00:00 app[worker.1]: TypeError: scdl.isValidUrl is not a function
2020-12-02T13:13:43.104174+00:00 app[worker.1]:     at Object.execute (/app/commands/play.js:42:21)
2020-12-02T13:13:43.104174+00:00 app[worker.1]:     at Client.<anonymous> (/app/index.js:78:13)
2020-12-02T13:13:43.104174+00:00 app[worker.1]:     at Client.emit (node:events:376:20)
2020-12-02T13:13:43.104175+00:00 app[worker.1]:     at MessageCreateAction.handle (/app/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
2020-12-02T13:13:43.104176+00:00 app[worker.1]:     at Object.module.exports [as MESSAGE_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
2020-12-02T13:13:43.104176+00:00 app[worker.1]:     at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
2020-12-02T13:13:43.104177+00:00 app[worker.1]:     at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
2020-12-02T13:13:43.104177+00:00 app[worker.1]:     at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
2020-12-02T13:13:43.104177+00:00 app[worker.1]:     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:132:16)
2020-12-02T13:13:43.104178+00:00 app[worker.1]:     at WebSocket.emit (node:events:376:20)
2020-12-02T13:13:43.193039+00:00 heroku[worker.1]: Process exited with status 1
2020-12-02T13:13:43.238538+00:00 heroku[worker.1]: State changed from up to crashed

**How To Reproduce**
1. Start the bot.
2. Use play (song name)
 
**Expected behavior**
A description of what you expected to happen.
The bot should have joined VC and started playing the music..

**Environment (add if possible)**

* Node.js version: 
Ofc 14

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by eritislami** [comment]
This was fixed, you must not be on the latest commit

**Comment by LUIS9799** [comment]
No, the bug has not been fixed yet  


I have the same problem

**Comment by eritislami** [comment]
> No, the bug has not been fixed yet
> 
> I have the same problem

Show me the error and your commit hash, based on the original post his code was not updated

**Comment by th13n-h4ck3r** [comment]
scdl had an update saying you must add `.default` at the end of the import line:

`const scdl = require("soundcloud-downloader").default;`

**Comment by YellowBanana508** [comment]
K
