### ISSUE TITLE
Live videos cannot be played by the bot

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#43]
Whenever i try to play a live video it throws this error. And the bot doesn't respond to any commands after this error. Also stop doesn't work.
```
(node:13448) UnhandledPromiseRejectionWarning: Error: FFmpeg/avconv not found!
    at Function.getInfo (D:\Other\Bot Coding\Bots\Ririchiyo Release 1.3\node_modules\prism-media\src\core\FFmpeg.js:130:11)
    at Function.create (D:\Other\Bot Coding\Bots\Ririchiyo Release 1.3\node_modules\prism-media\src\core\FFmpeg.js:143:38)
    at new FFmpeg (D:\Other\Bot Coding\Bots\Ririchiyo Release 1.3\node_modules\prism-media\src\core\FFmpeg.js:44:27)
    at D:\Other\Bot Coding\Bots\Ririchiyo Release 1.3\node_modules\ytdl-core-discord\index.js:35:24
    at D:\Other\Bot Coding\Bots\Ririchiyo Release 1.3\node_modules\ytdl-core-discord\node_modules\ytdl-core\lib\info.js:289:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:13448) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13448) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is the error after the stop command
```
(node:13448) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
TypeError: Cannot read property 'end' of null
    at Object.execute (D:\Other\Bot Coding\Bots\Ririchiyo Release 1.3\commands\stop.js:12:39)
    at Client.<anonymous> (D:\Other\Bot Coding\Bots\Ririchiyo Release 1.3\index.js:48:36)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (D:\Other\Bot Coding\Bots\Ririchiyo Release 1.3\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (D:\Other\Bot Coding\Bots\Ririchiyo Release 1.3\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (D:\Other\Bot Coding\Bots\Ririchiyo Release 1.3\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (D:\Other\Bot Coding\Bots\Ririchiyo Release 1.3\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (D:\Other\Bot Coding\Bots\Ririchiyo Release 1.3\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (D:\Other\Bot Coding\Bots\Ririchiyo Release 1.3\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
```

**Comment by alhassanv** [comment]
Refer to #42

**Comment by ParasDeshpande** [comment]
Thanks...
