### ISSUE TITLE
Bug: Error: Error parsing info: Unable to retrieve video metadata

### ISSUE THREAD

**Issue by AstethicDeath** [eritislami/evobot#467]
`(node:16359) UnhandledPromiseRejectionWarning: Error: Status code: 403
at ClientRequest.<anonymous> (/home/azuma/Bot/Criss/node_modules/miniget/dist/index.js:196:27)
at Object.onceWrapper (events.js:421:26)
at ClientRequest.emit (events.js:314:20)
at HTTPParser.parserOnIncomingClient (_http_client.js:601:27)
at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
at TLSSocket.socketOnData (_http_client.js:474:22)
at TLSSocket.emit (events.js:314:20)
at addChunk (_stream_readable.js:297:12)
at readableAddChunk (_stream_readable.js:272:9)
at TLSSocket.Readable.push (_stream_readable.js:213:10)
(node:16359) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16359) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: Error parsing info: Unable to retrieve video metadata
at getWatchPage (/home/azuma/Bot/Criss/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:75:13)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async exports.getBasicInfo (/home/azuma/Bot/Criss/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:84:22)
at async Map.getOrSet (/home/azuma/Bot/Criss/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/cache.js:24:19)
at async exports.getInfo (/home/azuma/Bot/Criss/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:226:14)
at async Map.getOrSet (/home/azuma/Bot/Criss/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/cache.js:24:19)
at async download (/home/azuma/Bot/Criss/node_modules/ytdl-core-discord/index.js:26:15)
at async play (/home/azuma/Bot/Criss/include/pyrex.js:31:18)`

**Comment by eritislami** [comment]
`/home/azuma/Bot/Criss/node_modules/ytdl-core-discord`

Use the latest package & package lock. Im no longer using ytdl-core-discord
