### ISSUE TITLE
Bot gets stuck if i play region blocked song...

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#52]
**Describe the bug**
Whenever i try to play a song that is blocked in my region the bot gives this error and does not respond to any more commands...
```
(node:11484) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
    at D:\Other\Bot Coding\Bots\Ririchiyo Release 1.3\node_modules\ytdl-core-discord\index.js:40:41
    at D:\Other\Bot Coding\Bots\Ririchiyo Release 1.3\node_modules\ytdl-core-discord\node_modules\ytdl-core\lib\info.js:289:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:11484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
The error should be properly handeled...

**Comment by eritislami** [comment]
Error is coming from ytdl-core-discord package, everything else is handled properly, i will check with the package author about this

**Comment by ParasDeshpande** [comment]
ok.

**Comment by ParasDeshpande** [comment]
@eritislami Do you have a discord server for evobot support?

**Comment by eritislami** [comment]
> @eritislami Do you have a discord server for evobot support?

No, you can join the official discord.js server for support which be better than asking me for support https://discord.gg/bRCvFy9

**Comment by ParasDeshpande** [comment]
Thanks...

**Comment by eritislami** [comment]
Relevant issue can be tracked here https://github.com/amishshah/ytdl-core-discord/issues/195
