### ISSUE TITLE
Bug: SCDL Is Valid Url Bug 

### ISSUE THREAD

**Issue by dylanjamesdev** [eritislami/evobot#552]
SCDL Is Valid Url Bug

Does the SCDL still have to be on a downgraded version?

```0|bot      | This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
0|bot      | TypeError: Cannot read property 'isValidUrl' of undefined
0|bot      |     at Object.execute (/root/tritan-bot/bot/src/handlers/commands/music/playlist.js:61:21)
0|bot      |     at module.exports (/root/tritan-bot/bot/src/handlers/events/message.js:370:13)
0|bot      |     at runMicrotasks (<anonymous>)
0|bot      |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|bot      | [Unhandled Rejection] TypeError: Cannot read property 'isValidUrl' of undefined
0|bot      |     at Object.execute (/root/tritan-bot/bot/src/handlers/commands/music/playlist.js:61:21)
0|bot      |     at module.exports (/root/tritan-bot/bot/src/handlers/events/message.js:370:13)
0|bot      |     at runMicrotasks (<anonymous>)
0|bot      |     at processTicksAndRejections (internal/process/task_queues.js:93:5)```

**Comment by dylanjamesdev** [comment]
Error at:
```    } else if (scdl.isValidUrl(args[0])) {
```

**Comment by dylanjamesdev** [comment]
In the play command as well.

```[Unhandled Rejection] TypeError: scdl.isValidUrl is not a function
0|bot      |     at Object.execute (/root/tritan-bot/bot/src/handlers/commands/music/play.js:47:21)
0|bot      |     at module.exports (/root/tritan-bot/bot/src/handlers/events/message.js:370:13)
0|bot      |     at processTicksAndRejections (internal/process/task_queues.js:93:5)```

**Comment by dylanjamesdev** [comment]
At `    } else if (scdl.isValidUrl(url) && url.includes("/sets/")) {`

**Comment by eritislami** [comment]
Answer these for me if you don't mind

- Are you on the latest commit
- What is the version of `soundcloud-downloader` in your package-lock.json
- How are you importing SCDL? this is the correct way `const scdl = require("soundcloud-downloader").default;`
- Are you getting this error with multiple different soundcloud links or just one

**Comment by totolerigolo324** [comment]
I had the same error before but just need to update `soundcloud-downloader`. Personally I am on version: `0.2.1`.

**Comment by miracl-cutelemon173** [comment]
Some new version of SCDL does not support IsValidUrl
Run
```npm remove soundcloud-downloader```
And run
```npm i soundcloud-downloader@0.1.6```
Finally run
```node index.js```
It should be working fine now.
