### ISSUE TITLE
Bug: Dockerfile and Heroku does not work.

### ISSUE THREAD

**Issue by yigitaltunay** [eritislami/evobot#586]
**Describe the bug**
Dockerfile and Heroku does not work. There is a problem with the npm package I made corrections but were not successful. Has anyone tried?

**How To Reproduce**
1. docker build -t  evobot .
2. etc.
 
**Expected behavior**
working in container technology

**Environment (add if possible)**
* Node.js version: Dockerfile node image version

**Additional information & screenshots**
![image](https://user-images.githubusercontent.com/46325656/105575206-06b7c700-5d7b-11eb-88f4-64f5e0dccaac.png)

Thanks..

**Comment by alsoGAMER** [comment]
Same issue here:

```
2021-01-24T16:44:50.270548+00:00 heroku[worker.1]: Starting process with command `node index.js`
2021-01-24T16:44:50.861927+00:00 heroku[worker.1]: State changed from starting to up
2021-01-24T16:44:52.006716+00:00 app[worker.1]: /app/node_modules/i18n/i18n.js:491
2021-01-24T16:44:52.006726+00:00 app[worker.1]: targetObject.locale = locales[targetLocale] ? targetLocale : defaultLocale
2021-01-24T16:44:52.006727+00:00 app[worker.1]: ^
2021-01-24T16:44:52.006727+00:00 app[worker.1]: 
2021-01-24T16:44:52.006728+00:00 app[worker.1]: TypeError: Cannot set property 'locale' of undefined
2021-01-24T16:44:52.006728+00:00 app[worker.1]: at Object.i18nSetLocale [as setLocale] (/app/node_modules/i18n/i18n.js:491:25)
2021-01-24T16:44:52.006729+00:00 app[worker.1]: at Object.<anonymous> (/app/commands/clip.js:3:6)
2021-01-24T16:44:52.006730+00:00 app[worker.1]: at Module._compile (node:internal/modules/cjs/loader:1108:14)
2021-01-24T16:44:52.006730+00:00 app[worker.1]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
2021-01-24T16:44:52.006730+00:00 app[worker.1]: at Module.load (node:internal/modules/cjs/loader:973:32)
2021-01-24T16:44:52.006731+00:00 app[worker.1]: at Function.Module._load (node:internal/modules/cjs/loader:813:14)
2021-01-24T16:44:52.006731+00:00 app[worker.1]: at Module.require (node:internal/modules/cjs/loader:997:19)
2021-01-24T16:44:52.006732+00:00 app[worker.1]: at require (node:internal/modules/cjs/helpers:92:18)
2021-01-24T16:44:52.006732+00:00 app[worker.1]: at Object.<anonymous> (/app/index.js:63:19)
2021-01-24T16:44:52.006733+00:00 app[worker.1]: at Module._compile (node:internal/modules/cjs/loader:1108:14)
2021-01-24T16:44:52.059712+00:00 heroku[worker.1]: Process exited with status 1
2021-01-24T16:44:52.107885+00:00 heroku[worker.1]: State changed from up to crashed
```

**Comment by WindSekirun** [comment]
@yigitaltunay @alsoGAMER add "locale": "en" into config.json will solve this issue.

**Comment by Abilleut** [comment]
I did what it said on the top but it didn't work for me, any other fixes?

**Comment by wolf-yuan-6115** [comment]
Dont use docker

**Comment by Abilleut** [comment]
i deleted docker, same thing happened

**Comment by Abilleut** [comment]
@wolf-yuan-6115 any other fixes?

**Comment by PanConKisu** [comment]
delete the .example from config.json.example

**Comment by wolf-yuan-6115** [comment]
> @wolf-yuan-6115 any other fixes?
> 

What is the error message from Heroku?

**Comment by wolf-yuan-6115** [comment]
And seems you didn't put `locales` in config.json
