### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Unbounder1** [eritislami/evobot#614]
When i try and get the queue, it says,
(node:246268) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/ryan/evobot/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.setup (/home/ryan/evobot/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)
    at new MessageEmbed (/home/ryan/evobot/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
    at embedLikes.map.e (/home/ryan/evobot/node_modules/discord.js/src/structures/APIMessage.js:166:40)
    at Array.map (<anonymous>)
    at APIMessage.resolveData (/home/ryan/evobot/node_modules/discord.js/src/structures/APIMessage.js:166:31)
    at TextChannel.send (/home/ryan/evobot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
    at Object.execute (/home/ryan/evobot/commands/queue.js:23:46)
    at Client.client.on (/home/ryan/evobot/index.js:108:13)
    at Client.emit (events.js:198:13)
(node:246268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 43)

**Comment by eritislami** [comment]
Update to nodejs 14
https://nodejs.org/en/
