### ISSUE TITLE
Bug: i can’t use the help command

### ISSUE THREAD

**Issue by itsbigboi** [eritislami/evobot#615]
**Describe the bug**
A description of what the bug is.
when i do /help i get "There was an error executing that command."

**How To Reproduce**
1.running the help command
2.
 
**Expected behavior**
A description of what you expected to happen. show the commands

**Comment by eritislami** [comment]
Would help if you would share the error as well.

**Comment by emunand** [comment]
hey there, im havin the same error, here's what the bot spits out:
`TypeError: fields.flat is not a function
    at Function.normalizeFields (/srv/jmusic/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.addFields (/srv/jmusic/node_modules/discord.js/src/structures/MessageEmbed.js:266:42)
    at MessageEmbed.addField (/srv/jmusic/node_modules/discord.js/src/structures/MessageEmbed.js:257:17)
    at commands.forEach (/srv/jmusic/commands/help.js:20:17)
    at Array.forEach (<anonymous>)
    at Object.execute (/srv/jmusic/commands/help.js:19:14)
    at Client.client.on (/srv/jmusic/index.js:108:13)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (/srv/jmusic/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/srv/jmusic/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)`

**Comment by booleans-oss** [comment]
You need to update Discord.js

**Comment by eritislami** [comment]
Not a bug
