### ISSUE TITLE
Bug: Status Code: 429

### ISSUE THREAD

**Issue by Larkify** [eritislami/evobot#623]
So I understand that this means that too many requests are being sent, but the thing is... there really aren't that many requests I'm sending but I just keep getting this error. 

I don't support anyone knows why or how to fix it?

**Comment by henry-bao** [comment]
I don't think there is a way to "fix" the issue since it is not really a bug in the first place. All you could do is either switch IP or wait for a couple of days.

**Comment by Larkify** [comment]
> I don't think there is a way to "fix" the issue since it is not really a bug in the first place. All you could do is either switch IP or wait for a couple of days.
> Edit: Found other posts on GitHub saying that set cookies to all methods requests could possibly fix the issue, should probably look into that 👀

The only thing is, I don't know much about this kinda stuff. Hence the reason for me using EvoBot.

**Comment by Takiyo0** [comment]
If the error from miniget, yes you have to wait or switch IP. If you don't have another IP, you have to wait for about 30m - 3h until you can use it back. I just get this 429 and waited for 2h. If you're on heroku, you can try restarting your bot multiple times. Idk if it's because heroku changing the IP every we restart or not, and If you're lucky, you won't get 429 anymore

**Comment by henry-bao** [comment]
> > I don't think there is a way to "fix" the issue since it is not really a bug in the first place. All you could do is either switch IP or wait for a couple of days.
> > Edit: Found other posts on GitHub saying that set cookies to all methods requests could possibly fix the issue, should probably look into that 👀
> 
> The only thing is, I don't know much about this kinda stuff. Hence the reason for me using EvoBot.

Well then... the only thing you could really do is wait or switch IP

**Comment by mozzi-berilinky** [comment]
I want to do it the first way, but an error appears in the YouTube console window and I can't find document.cookie.

![error](https://user-images.githubusercontent.com/67187351/107148659-ca4db300-6997-11eb-8ff5-1a2cb45ce07e.png)

And in which file should these codes be put?

**Comment by henry-bao** [comment]
> I want to do it the first way, but an error appears in the YouTube console window and I can't find document.cookie.
> 
> ![error](https://user-images.githubusercontent.com/67187351/107148659-ca4db300-6997-11eb-8ff5-1a2cb45ce07e.png)
> 
> And should this code be put in the command/play.js file?

Hi, you can ignore those errors, and you have to type `document.cookie` into the console yourself.

**Comment by Larkify** [comment]
**UPDATE:** It's been just under a week since I opened this Issue. I left the bot offline for a night, and it was working in the morning and fine the following days. It's only today that it decided to have an issue. The thing is, switching IP isn't easy as I host with [repl.it](https://repl.it) and use [UptimeRobot](https://uptimerobot.com/) to keep it alive. As I am new to this, I'll try this Cookie Sending solution but I'm not sure how that'll go. Wish me luck 😂

**Comment by Tomato6966** [comment]
Hey For everyone WHAT IS 429

First google has restricted Calling amounts, if u use the google-api (as in this Bot) you are limited to those.
10000 Units per day, if you go over that then you will be blocked (Its like 20/song) there is also a week limit which almost nobody knows...

If u manage to get a 429,then it means that you have reached the limit. Now google blocks your IP ADRESS for some hours/days, ...

After that you can use it again, yeeee


**BUT WAIT** you can go ahead of this by using that in ytdl-core search/play command options
```
requestOptions: {
  headers {
    cookie: "YOUTUBE_COOKIE"
  }
}
```
ofc. you need to replace the YOUTUBE_COOKIE with your actual youtube cookie.
[CLICK HERE TO SEE HOW](https://github.com/fent/node-ytdl-core/blob/784c04eaf9f3cfac0fe0933155adffe0e2e0848a/example/cookies.js#L6-L12)
Short description, go in a SIGNED IN youtube account on the website [youtube.com](https://youtube.com)
Then press f12 to see the source code, now click on the "NETWORK" Tab and press f5 to reload the page.
Now go to a request (Post) Tab where youtube.com the name is. There scroll down on the new Tab to find the COOKIE

It should look something similar to this:
```
VISITOR_INFO1_LIVE=3KQr-4lKFhM; CONSENT=YES+AT.de+20160424-15-0; _ga=GA1.2.676939780.1569437549; PREF=f1=50000000&cvdm=grid&f5=20030&al=de; YSC=XXXXXXXXXXXXXXX; SID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.; __Secure-3PSID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.; HSID=XXXXXXXXXXXXXXXXX; SSID=XXXXXXXXXXXXXXXXXXXXXX; APISID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; SAPISID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; __Secure-3PAPISID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; LOGIN_INFO=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; SIDCC=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-X_XXXXXXXXXXXXXXXXX; __Secure-3PSIDCC=XXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXX_XXXXXXXXXXXXXXXXXXXXXXXXX
```
*X==some letters*

IF Your cookie is not WORKING, then make sure it is LONG and similar to mine
IF Your cookie is STILL NOT WORKING, then REFRESH all cookies, by deleting them in your BROWSER CACHE


I HOPE THIS HELPS ;)

**Comment by dlcoals** [comment]
I put the code of the cookie method in the command/play.js file, but the 429 error occurs the same, and refreshing the cookie does not solve it. I tried using a proxy, but it seems to delay the 429 error rather than prevent it.

**Comment by Larkify** [comment]
**There are tons of replies here, so if you're visiting here then follow one of them.** 
Any issues, contact the author of the comment.

**Comment by shkour** [comment]
> > > I don't think there is a way to "fix" the issue since it is not really a bug in the first place. All you could do is either switch IP or wait for a couple of days.
> > > Edit: Found other posts on GitHub saying that set cookies to all methods requests could fix the issue, should probably look into that 👀
> > 
> > 
> > The only thing is, I don't know much about this kinda stuff. Hence the reason for me using EvoBot.
> 
> Well then... the only thing you could really do is wait or switch IP
> 
> **EDIT:**
> This might fix
> 
> ```js
> const COOKIE = "yourcookie"; // Go to youtube homepage -> Inspect Element -> type document.cookie in console. Paste that cookie string here
> const token = 'youtube_id_token'; // go to youtube homepage -> CTRL + U to view source -> CTRL + F and search for ID_TOKEN and paste the string here
> 
> // your stream downloader
> ytdl(url, {
>     requestOptions: {
>         headers: {
>             cookie: COOKIE,
>             'x-youtube-identity-token': token
>         }
>     }
> });
> ```
> 
> **EDIT2:**
> Found another method using proxy
> 
> ```js
> const https = require('https-proxy-agent');
> const proxy = 'http://123.123.123.123:8080'; //http://user:pass@​123.123.123.123:8080 - Remove user:pass if your proxy doesn't require a authentication.
> const agent = https(proxy);
> 
> ytdl(url, {
>     requestOptions: { agent }
> });
> ```
> 
> **Note:** Cookie method won't work if you're already 429'ed
> 
> **EDIT3:** The cookie method worked for me after switching IP. I am limit testing right now with the bot running in 4 servers on loop to see if I will get 429'ed again.
> 
> **EDIT4:** After 24hours of non-stop playing on 4 servers, I haven't gotten the 429 error

What is the file to which these codes were added

**Comment by wolf-yuan-6115** [comment]
Dear users...
Why don't host bot on Heroku
if you get 429, restart dyno and it will be fixed

**Comment by henry-bao** [comment]
> Dear users...
> Why don't host bot on Heroku
> if you get 429, restart dyno and it will be fixed

That's not really a long-term solution tho, it will be tedious as your bot grows

**Comment by henry-bao** [comment]
> > > > I don't think there is a way to "fix" the issue since it is not really a bug in the first place. All you could do is either switch IP or wait for a couple of days.
> > > > Edit: Found other posts on GitHub saying that set cookies to all methods requests could fix the issue, should probably look into that 👀
> > > 
> > > 
> > > The only thing is, I don't know much about this kinda stuff. Hence the reason for me using EvoBot.
> > 
> > 
> > Well then... the only thing you could really do is wait or switch IP
> > **EDIT:**
> > This might fix
> > ```js
> > const COOKIE = "yourcookie"; // Go to youtube homepage -> Inspect Element -> type document.cookie in console. Paste that cookie string here
> > const token = 'youtube_id_token'; // go to youtube homepage -> CTRL + U to view source -> CTRL + F and search for ID_TOKEN and paste the string here
> > 
> > // your stream downloader
> > ytdl(url, {
> >     requestOptions: {
> >         headers: {
> >             cookie: COOKIE,
> >             'x-youtube-identity-token': token
> >         }
> >     }
> > });
> > ```
> > 
> > 
> > **EDIT2:**
> > Found another method using proxy
> > ```js
> > const https = require('https-proxy-agent');
> > const proxy = 'http://123.123.123.123:8080'; //http://user:pass@​123.123.123.123:8080 - Remove user:pass if your proxy doesn't require a authentication.
> > const agent = https(proxy);
> > 
> > ytdl(url, {
> >     requestOptions: { agent }
> > });
> > ```
> > 
> > 
> > **Note:** Cookie method won't work if you're already 429'ed
> > **EDIT3:** The cookie method worked for me after switching IP. I am limit testing right now with the bot running in 4 servers on loop to see if I will get 429'ed again.
> > **EDIT4:** After 24hours of non-stop playing on 4 servers, I haven't gotten the 429 error
> 
> What is the file to which these codes were added?

Hi, basically everywhere that the `ytdl` package is used you need to add a cookie or proxy request header

**Comment by Itz-MrJ** [comment]
> > > I don't think there is a way to "fix" the issue since it is not really a bug in the first place. All you could do is either switch IP or wait for a couple of days.
> > > Edit: Found other posts on GitHub saying that set cookies to all methods requests could fix the issue, should probably look into that 👀
> > 
> > 
> > The only thing is, I don't know much about this kinda stuff. Hence the reason for me using EvoBot.
> 
> Well then... the only thing you could really do is wait or switch IP
> 
> **EDIT:**
> This might fix
> 
> ```js
> const COOKIE = "yourcookie"; // Go to youtube homepage -> Inspect Element -> type document.cookie in console. Paste that cookie string here
> const token = 'youtube_id_token'; // go to youtube homepage -> CTRL + U to view source -> CTRL + F and search for ID_TOKEN and paste the string here
> 
> // your stream downloader
> ytdl(url, {
>     requestOptions: {
>         headers: {
>             cookie: COOKIE,
>             'x-youtube-identity-token': token
>         }
>     }
> });
> ```
> 
> **EDIT2:**
> Found another method using proxy
> 
> ```js
> const https = require('https-proxy-agent');
> const proxy = 'http://123.123.123.123:8080'; //http://user:pass@​123.123.123.123:8080 - Remove user:pass if your proxy doesn't require a authentication.
> const agent = https(proxy);
> 
> ytdl(url, {
>     requestOptions: { agent }
> });
> ```
> 
> **Note:** Cookie method won't work if you're already 429'ed
> 
> **EDIT3:** The cookie method worked for me after switching IP. I am limit testing right now with the bot running in 4 servers on loop to see if I will get 429'ed again.
> 
> **EDIT4:** After 24hours of non-stop playing on 4 servers, I haven't gotten the 429 error

Hey, I tried getting the cookie and id_token and pasted them in their respective positions. Now I'm getting an error saying url is not defined.
_ReferenceError: url is not defined at Object.<anonymous> (/home/runner/GracefulOilyIntroductory/commands/play.js:17:6)_

**Comment by henry-bao** [comment]
> > > > I don't think there is a way to "fix" the issue since it is not really a bug in the first place. All you could do is either switch IP or wait for a couple of days.
> > > > Edit: Found other posts on GitHub saying that set cookies to all methods requests could fix the issue, should probably look into that 👀
> > > 
> > > 
> > > The only thing is, I don't know much about this kinda stuff. Hence the reason for me using EvoBot.
> > 
> > 
> > Well then... the only thing you could really do is wait or switch IP
> > **EDIT:**
> > This might fix
> > ```js
> > const COOKIE = "yourcookie"; // Go to youtube homepage -> Inspect Element -> type document.cookie in console. Paste that cookie string here
> > const token = 'youtube_id_token'; // go to youtube homepage -> CTRL + U to view source -> CTRL + F and search for ID_TOKEN and paste the string here
> > 
> > // your stream downloader
> > ytdl(url, {
> >     requestOptions: {
> >         headers: {
> >             cookie: COOKIE,
> >             'x-youtube-identity-token': token
> >         }
> >     }
> > });
> > ```
> > 
> > 
> > **EDIT2:**
> > Found another method using proxy
> > ```js
> > const https = require('https-proxy-agent');
> > const proxy = 'http://123.123.123.123:8080'; //http://user:pass@​123.123.123.123:8080 - Remove user:pass if your proxy doesn't require a authentication.
> > const agent = https(proxy);
> > 
> > ytdl(url, {
> >     requestOptions: { agent }
> > });
> > ```
> > 
> > 
> > **Note:** Cookie method won't work if you're already 429'ed
> > **EDIT3:** The cookie method worked for me after switching IP. I am limit testing right now with the bot running in 4 servers on loop to see if I will get 429'ed again.
> > **EDIT4:** After 24hours of non-stop playing on 4 servers, I haven't gotten the 429 error
> 
> Hey, I tried getting the cookie and id_token and pasted them in their respective positions. Now I'm getting an error saying url is not defined.
> _ReferenceError: url is not defined at Object. (/home/runner/GracefulOilyIntroductory/commands/play.js:17:6)_

Hi there, `url` is the YouTube video(s) you are trying to get information from, you have to define that yourself
