### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by psavex25** [eritislami/evobot#676]
**Describe the bug**
 Cannot set property 'locale' of undefined on startup crashing

**How To Reproduce**
1.
2.
 
**Expected behavior**
 Cannot set property 'locale' of undefined

**Environment (add if possible)**
* Node.js version: 14.16.0

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by Abilleut** [comment]
2021-03-10T22:21:07.151711+00:00 heroku[worker.1]: Starting process with command `node index.js`
2021-03-10T22:21:07.810404+00:00 heroku[worker.1]: State changed from starting to up
2021-03-10T22:21:10.420127+00:00 heroku[worker.1]: Process exited with status 1
2021-03-10T22:21:10.523462+00:00 heroku[worker.1]: State changed from up to crashed
2021-03-10T22:21:10.353402+00:00 app[worker.1]: /app/node_modules/i18n/i18n.js:491
2021-03-10T22:21:10.353438+00:00 app[worker.1]:     targetObject.locale = locales[targetLocale] ? targetLocale : defaultLocale
2021-03-10T22:21:10.353438+00:00 app[worker.1]:                         ^
2021-03-10T22:21:10.353439+00:00 app[worker.1]: 
2021-03-10T22:21:10.353440+00:00 app[worker.1]: TypeError: Cannot set property 'locale' of undefined
2021-03-10T22:21:10.353440+00:00 app[worker.1]:     at Object.i18nSetLocale [as setLocale] (/app/node_modules/i18n/i18n.js:491:25)
2021-03-10T22:21:10.353441+00:00 app[worker.1]:     at Object.<anonymous> (/app/commands/clip.js:3:6)
2021-03-10T22:21:10.353441+00:00 app[worker.1]:     at Module._compile (node:internal/modules/cjs/loader:1092:14)
2021-03-10T22:21:10.353442+00:00 app[worker.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
2021-03-10T22:21:10.353442+00:00 app[worker.1]:     at Module.load (node:internal/modules/cjs/loader:972:32)
2021-03-10T22:21:10.353442+00:00 app[worker.1]:     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
2021-03-10T22:21:10.353442+00:00 app[worker.1]:     at Module.require (node:internal/modules/cjs/loader:996:19)
2021-03-10T22:21:10.353443+00:00 app[worker.1]:     at require (node:internal/modules/cjs/helpers:92:18)
2021-03-10T22:21:10.353443+00:00 app[worker.1]:     at Object.<anonymous> (/app/index.js:63:19)
2021-03-10T22:21:10.353444+00:00 app[worker.1]:     at Module._compile (node:internal/modules/cjs/loader:1092:14)

same issue here please help

**Comment by Maks1116** [comment]
You have set locale on config.json, but this locale does not exists
