### ISSUE TITLE
Search command optimizations

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#70]
**Describe the bug**
1. Empty search query can be submitted using \search
2. There is no way to stop the collector.
3. The collector does not work on reply sometimes.
4.The searhed song when played throws the error below...

**How To Reproduce**
1.Use \search command without any search query.
 
**Expected behavior**
The bot should further explain on how to use \search on giving empty query instead of executing the command.
There should be a response that can close the collector.

**Environment (add if possible)**
* Node.js version: ^12.0

Also got this error upon trying to play...
```
(node:14416) UnhandledPromiseRejectionWarning: Error: FFmpeg/avconv not found!
    at Function.getInfo (D:\Other\Bot Coding\Bots\Currently Working\Ririchiyo Music V-0.4.0\src\node_modules\prism-media\src\core\FFmpeg.js:130:11)   
    at Function.create (D:\Other\Bot Coding\Bots\Currently Working\Ririchiyo Music V-0.4.0\src\node_modules\prism-media\src\core\FFmpeg.js:143:38)    
    at new FFmpeg (D:\Other\Bot Coding\Bots\Currently Working\Ririchiyo Music V-0.4.0\src\node_modules\prism-media\src\core\FFmpeg.js:44:27)
    at D:\Other\Bot Coding\Bots\Currently Working\Ririchiyo Music V-0.4.0\src\node_modules\ytdl-core-discord\index.js:35:24
    at D:\Other\Bot Coding\Bots\Currently Working\Ririchiyo Music V-0.4.0\src\node_modules\ytdl-core-discord\node_modules\ytdl-core\lib\info.js:288:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:14416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14416) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Also i get this error when trying to skip that
```
TypeError: Cannot read property 'end' of null
    at Object.execute (D:\Other\Bot Coding\Bots\Currently Working\Ririchiyo Music V-0.4.0\src\commands\skip.js:14:33)
    at Client.<anonymous> (D:\Other\Bot Coding\Bots\Currently Working\Ririchiyo Music V-0.4.0\src\index.js:50:15)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (D:\Other\Bot Coding\Bots\Currently Working\Ririchiyo Music V-0.4.0\src\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (D:\Other\Bot Coding\Bots\Currently Working\Ririchiyo Music V-0.4.0\src\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (D:\Other\Bot Coding\Bots\Currently Working\Ririchiyo Music V-0.4.0\src\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (D:\Other\Bot Coding\Bots\Currently Working\Ririchiyo Music V-0.4.0\src\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (D:\Other\Bot Coding\Bots\Currently Working\Ririchiyo Music V-0.4.0\src\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (D:\Other\Bot Coding\Bots\Currently Working\Ririchiyo Music V-0.4.0\src\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
```

**Comment by eritislami** [comment]
Will work on optimizing this command soon, also the error happens because you are missing ffmpeg on your system

**Comment by ParasDeshpande** [comment]
The ffmpeg error did not use to occur on earlier versions tho.... How do i install it?

**Comment by eritislami** [comment]
> The ffmpeg error did not use to occur on earlier versions tho.... How do i install it?

from https://ffmpeg.org/ or `npm i ffmpeg-static`

**Comment by ParasDeshpande** [comment]
ok thanks...

**Comment by eritislami** [comment]
Pushed changes b0077d265a93eb08d7dbb15a664110e4e73ed8dc & 1832316618b9d6d40fe0640fe5275768e7694cbd

**Comment by ParasDeshpande** [comment]
Works... But i think you should add a way to cancel search (doesent matter that much because of the 30 secs timeout).

Also whenever the started playing message is deleted this error shows up... This doesn't affect the bot... But i think there might be an extra message delete somewhere after already deleting the started playing message.

Here's the error,
```
DiscordAPIError: Unknown Message
    at RequestHandler.execute (D:\Other\Bot Coding\Bots\Currently Working\Ririchiyo Music V-0.4.0\src\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  method: 'delete',
  path: '/channels/718919267923263491/messages/721446556552658966/reactions',
  code: 10008,
  httpStatus: 404
}
```
