### ISSUE TITLE
Bug: Emoji Deletion Error

### ISSUE THREAD

**Issue by rexjohannes** [eritislami/evobot#727]
**Describe the bug**
The Bot dont remove the Emoji Reaction on Player Embed
**How To Reproduce**
1. play something
2. reacet to stop or other reaction
 
**Expected behavior**
DiscordAPIError: Two factor is required for this operation
    at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'delete',
  path: '/channels/637374846900240394/messages/840126674681987073/reactions',
  code: 60003,
  httpStatus: 403
}

**Environment (add if possible)**
* Node.js version: v14

**Additional information & screenshots**

https://cdn.kurwa.club/files/hvWG3.png
https://cdn.kurwa.club/files/oMBE7.png

**Comment by wolf-yuan-6115** [comment]
Error 60003 is a known error.
Try to disable server 2FA and try again.
