### ISSUE TITLE
Bug: Playlist commands can be used even when music is not playing.

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#73]
**Describe the bug**
Although not entirely a bug, if the bot somehow fails to leave the voice channel and someone types the following commands, they still run and cause errors.

**How To Reproduce**
1.Make the bot join a channel(Sometimes the bot might not leave)
2.Use (skip, stop, resume, pause) commands
 
**Expected behavior**
The bot should respond with "There is nothing playing."

**Environment (add if possible)**
* Node.js version: ^12.0.x

**Additional information & screenshots**
[Screenshot of executing commands while no music was playing]
![Capture4](https://user-images.githubusercontent.com/63962807/84579308-4d5b4100-adea-11ea-81ae-510e31524bcb.PNG)

Also the resume command caused this error-
```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:266:14)
    at StreamDispatcher.Writable.write (_stream_writable.js:315:5)
    at Encoder.ondata (_stream_readable.js:717:22)
    at Encoder.emit (events.js:315:20)
    at Encoder.Readable.read (_stream_readable.js:506:10)
    at flow (_stream_readable.js:1006:34)
    at resume_ (_stream_readable.js:987:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
(node:13228) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'channel' of undefined
    at Object.play (D:\Other\Bot Coding\Bots\Currently Working\evobot\src\include\play.js:10:13)
    at StreamDispatcher.<anonymous> (D:\Other\Bot Coding\Bots\Currently Working\evobot\src\include\play.js:51:26)
    at StreamDispatcher.emit (events.js:327:22)
    at finishMaybe (_stream_writable.js:639:14)
    at _stream_writable.js:616:5
    at StreamDispatcher._final (D:\Other\Bot Coding\Bots\Currently Working\evobot\src\node_modules\discord.js\src\client\voice\dispatcher\StreamDispatcher.js:248:5)
    at callFinal (_stream_writable.js:609:10)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:13228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:13228) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of null
    at Encoder._transform (D:\Other\Bot Coding\Bots\Currently Working\evobot\src\node_modules\prism-media\src\opus\Opus.js:142:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:13228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
no changes were made to the code except adding additional commands which were not executed during this error...

**Comment by eritislami** [comment]
It happens when the streamdispatcher fails to end properly, like when connection is lost while playing music or some other problem, i dont know if anything can be done for this since the stream data is controlled by d.js/prism-media
