### ISSUE TITLE
Instantly dies when heroku starts bot

### ISSUE THREAD

**Issue by Someonexddd** [eritislami/evobot#758]
Hi whenever i upload the bot to heroku i get these errors and it dies

logs:

2021-06-04T22:03:49.889017+00:00 app[worker.1]:     at Object.compileFunction (node:vm:353:18)

2021-06-04T22:03:49.889017+00:00 app[worker.1]:     at wrapSafe (node:internal/modules/cjs/loader:1039:15)

2021-06-04T22:03:49.889018+00:00 app[worker.1]:     at Module._compile (node:internal/modules/cjs/loader:1073:27)

2021-06-04T22:03:49.889018+00:00 app[worker.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)

2021-06-04T22:03:49.889018+00:00 app[worker.1]:     at Module.load (node:internal/modules/cjs/loader:989:32)

2021-06-04T22:03:49.889019+00:00 app[worker.1]:     at Function.Module._load (node:internal/modules/cjs/loader:829:14)

2021-06-04T22:03:49.889019+00:00 app[worker.1]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)

2021-06-04T22:03:49.889019+00:00 app[worker.1]:     at node:internal/main/run_main_module:17:47

2021-06-04T22:03:49.927026+00:00 heroku[worker.1]: Process exited with status 1

2021-06-04T22:03:50.087651+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by Someonexddd** [comment]
This started after I updated the bot since it didnt work anymore (it gave error 403)

**Comment by Someonexddd** [comment]
when I then restart it i get 

2021-06-04T22:16:28.663304+00:00 heroku[worker.1]: Process exited with status 1

2021-06-04T22:16:28.687576+00:00 heroku[worker.1]: State changed from up to crashed

2021-06-04T22:16:28.624286+00:00 app[worker.1]: /app/node_modules/i18n/i18n.js:491

2021-06-04T22:16:28.624309+00:00 app[worker.1]:     targetObject.locale = locales[targetLocale] ? targetLocale : defaultLocale

2021-06-04T22:16:28.624310+00:00 app[worker.1]:                         ^

2021-06-04T22:16:28.624310+00:00 app[worker.1]: 

2021-06-04T22:16:28.624310+00:00 app[worker.1]: TypeError: Cannot set property 'locale' of undefined

2021-06-04T22:16:28.624311+00:00 app[worker.1]:     at Object.i18nSetLocale [as setLocale] (/app/node_modules/i18n/i18n.js:491:25)

2021-06-04T22:16:28.624311+00:00 app[worker.1]:     at Object.<anonymous> (/app/commands/clip.js:3:6)

2021-06-04T22:16:28.624311+00:00 app[worker.1]:     at Module._compile (node:internal/modules/cjs/loader:1109:14)

2021-06-04T22:16:28.624312+00:00 app[worker.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)

2021-06-04T22:16:28.624312+00:00 app[worker.1]:     at Module.load (node:internal/modules/cjs/loader:989:32)

2021-06-04T22:16:28.624312+00:00 app[worker.1]:     at Function.Module._load (node:internal/modules/cjs/loader:829:14)

2021-06-04T22:16:28.624312+00:00 app[worker.1]:     at Module.require (node:internal/modules/cjs/loader:1013:19)

2021-06-04T22:16:28.624313+00:00 app[worker.1]:     at require (node:internal/modules/cjs/helpers:93:18)

2021-06-04T22:16:28.624313+00:00 app[worker.1]:     at Object.<anonymous> (/app/index.js:63:19)

2021-06-04T22:16:28.624313+00:00 app[worker.1]:     at Module._compile (node:internal/modules/cjs/loader:1109:14)

**Comment by wolf-yuan-6115** [comment]
Put correct locale in config.json

**Comment by Someonexddd** [comment]
fixed it im a dumbass, apparently the config.json was being gitignored
