### ISSUE TITLE
Bug: Invite command does not work

### ISSUE THREAD

**Issue by Nisarga-Developer** [eritislami/evobot#782]
The invite command to give the invite link doesn't work

**Comment by wolf-yuan-6115** [comment]
What kind of *doesn't work*
Is Discord said it's not an valid application ID or scope is incorrect or something else?

**Comment by Nisarga-Developer** [comment]
> What kind of _doesn't work_
> Is Discord said it's not an valid application ID or scope is incorrect or something else?

Bot doesn't reply anything. All the other commands work fine though.

**Comment by eritislami** [comment]
It sends the link in a private DM, maybe you have blocked dms or some other reason

![](https://i.imgur.com/b3aCCpK.png)

**Comment by Nisarga-Developer** [comment]
No I didn't block the bot.

**Comment by Nisarga-Developer** [comment]
Neither I have blocked DMs

**Comment by Nisarga-Developer** [comment]
I got this log```
 DiscordAPIError: Missing Permissions
    at RequestHandler.execute (/home/evobot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (/home/evobot/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'delete',
  path: '/channels/856536074665852941/messages/858664758533160970/reactions',
  code: 50013,
  httpStatus: 403
}
DiscordAPIError: Cannot send messages to this user
    at RequestHandler.execute (/home/evobot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (/home/evobot/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'post',
  path: '/channels/858567681862402068/messages',
  code: 50007,
  httpStatus: 403
}
```

**Comment by eritislami** [comment]
Check this setting in privacy

![](https://i.imgur.com/3yRnnIe.png)

**Comment by Nisarga-Developer** [comment]
![image](https://user-images.githubusercontent.com/45588772/123547416-52cdc400-d77e-11eb-930a-e4d43ec1b51f.png)
I already did that

**Comment by Nisarga-Developer** [comment]
Thank you for your help @eritislami ! It's now working.
