### ISSUE TITLE
Bug: help command not work

### ISSUE THREAD

**Issue by Bruciemm** [eritislami/evobot#883]
whenever i run the command help it brings up this error:
TypeError: fields.flat is not a function
at Function.normalizeFields (/home/container/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
at MessageEmbed.addFields (/home/container/node_modules/discord.js/src/structures/MessageEmbed.js:266:42)
at MessageEmbed.addField (/home/container/node_modules/discord.js/src/structures/MessageEmbed.js:257:17)
at commands.forEach (/home/container/commands/help.js:17:17)
at Array.forEach (<anonymous>)
at Object.execute (/home/container/commands/help.js:16:14)
at Client.client.on (/home/container/index.js:82:13)
at Client.emit (events.js:189:13)
at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)

not sure why as the other commands work properly but would be nice to have it fixed

**Comment by eritislami** [comment]
Well then update your ancient nodejs version to 14 https://nodejs.org/en/
