### ISSUE TITLE
Bug: Soundcloud list crash

### ISSUE THREAD

**Issue by RiemaruKarurosu** [eritislami/evobot#884]
**Describe the bug**
Soundcloud list crashes the bot

**How To Reproduce**
1. /play https://soundcloud.com/quark064/section-4-battle-theme-paper?in=agent_m12/sets/paper-mario-the-origami-king

 
**Expected behavior**
Get soundcloud audio

**Environment (add if possible)**
* Node.js version: 16.9.0

**Additional information & screenshots**

Crash output:

at __spreadArrays (D:\github\heroku\node_modules\soundcloud-downloader\dist\info.js:39:82)
    at D:\github\heroku\node_modules\soundcloud-downloader\dist\info.js:100:24
    at step (D:\github\heroku\node_modules\soundcloud-downloader\dist\info.js:33:23)
    at Object.next (D:\github\heroku\node_modules\soundcloud-downloader\dist\info.js:14:53)
    at fulfilled (D:\github\heroku\node_modules\soundcloud-downloader\dist\info.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by eritislami** [comment]
Try the below examples, I'm not sure why its not working with your original link, i don't maintain the soundcloud-downloader package so I can't do anything about it.

/play https://soundcloud.com/agent_m12/sets/paper-mario-the-origami-king
or
/playlist https://soundcloud.com/agent_m12/sets/paper-mario-the-origami-king
