### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by jordanlol** [eritislami/evobot#89]
Error: Cannot find module 'discord.js'
Require stack:
- C:\Users\USER\Desktop\evobot-master\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\USER\Desktop\evobot-master\index.js:4:32)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',

**Comment by mmoomocow** [comment]
I believe the issue is that you didn't run `npm install` before starting the project
```
at Object. (C:\Users\USER\Desktop\evobot-master\index.js:4:32)
```
on this line is
```js
const { Client, Collection } = require("discord.js");
```

To solve this, go to your project file and run the command `npm install` see [🚀 Getting Started](https://github.com/eritislami/evobot#-getting-started)
