### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Tali13** [eritislami/evobot#896]
npm start

> evobot@0.14.0 start /home/runner/evobot-1
> node index.js

/home/runner/evobot-1/node_modules/simple-youtube-api/src/index.js:26
        if (typeof key !== 'string') throw new Error('The YouTube API key you provided was not a string.');
                                     ^

Error: The YouTube API key you provided was not a string.
    at new YouTube (/home/runner/evobot-1/node_modules/simple-youtube-api/src/index.js:26:44)
    at Object.<anonymous> (/home/runner/evobot-1/commands/play.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/evobot-1/index.js:39:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! evobot@0.14.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the evobot@0.14.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-09-17T16_25_42_233Z-debug.log
exit status 1|

pls help

**Comment by eritislami** [comment]
Is your config.json file valid? https://jsonlint.com/

**Comment by Tali13** [comment]
![image](https://user-images.githubusercontent.com/87566705/133827351-2e6400c5-f426-460e-a285-94fed36e1403.png)

**Comment by Tali13** [comment]
it def file

**Comment by Tali13** [comment]
i didn't change anything

**Comment by Tali13** [comment]
oh
i fixed it
