### ISSUE TITLE
Bug: clip xxx.mp3

### ISSUE THREAD

**Issue by Hiura-Souji** [eritislami/evobot#921]
**Describe the bug**
clip xxx.mp3 error

**How To Reproduce**
1. clip xxx.mp3
2. can't run
 
**Expected behavior**
A description of what you expected to happen.

**Environment (add if possible)**
* Node.js version: 14.17.6

**Additional information & screenshots**

X:\evobot>node index.js
Bot ready!
Collection(0) [Map] {}
DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (X:\evobot\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async RequestHandler.push (X:\evobot\node_modules\discord.js\src\rest\RequestHandler.js:39:14) {
  method: 'post',
  path: '/channels/(NUMBER)/messages',
  code: 50006,
  httpStatus: 400
}

**Comment by eritislami** [comment]
Try /clip xxx without .mp3 at the end
