### ISSUE TITLE
Bug: statusCode: 410

### ISSUE THREAD

**Issue by Hiura-Souji** [eritislami/evobot#934]
**Describe the bug**
statusCode: 410
THANK YOU~

**How To Reproduce**
1. !P YOASOBI「夜に駆ける」 Official Music Video
2.  statusCode: 410
3. Maybe just this type have error...I user other title is ok.
 
**Expected behavior**
A description of what you expected to happen.

**Environment (add if possible)**
* Node.js version: 14

**Additional information & screenshots**
X:\evobot>node index.js
BOT ready!
MinigetError: Status code: 410
    at ClientRequest.<anonymous> (X:\evobot\node_modules\miniget\dist\index.js:211:27)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10) {
  statusCode: 410

**Comment by eritislami** [comment]
410 Gone client error response code indicates that access to the target resource is no longer available at the origin server

**Comment by Hiura-Souji** [comment]
> 410 消失的用戶端錯誤回應代碼表示原始器不再可用對目標資源的訪問

https://www.youtube.com/watch?v=x8VYWazR5mE
But it can watch on chrome,
It's have button, click it can watch video

**Comment by eritislami** [comment]
> > 410 消失的用戶端錯誤回應代碼表示原始器不再可用對目標資源的訪問
> 
> https://www.youtube.com/watch?v=x8VYWazR5mE
> But it can watch on chrome,
> It's have button, click it can watch video

Sure but its not available via API, its restricted, not a bug

**Comment by Hiura-Souji** [comment]
> > > 410 消失的用戶端錯誤回應代碼表示原始器不再可用對目標資源的訪問
> > 
> > 
> > https://www.youtube.com/watch?v=x8VYWazR5mE但它可以在鉻上觀看，它有按鈕， 點擊它可以看視頻
> 
> 當然可以， 但它不能通過 Api， 它的限制， 而不是一個錯誤

I got it
Sorry to trouble you
Thank you
