### ISSUE TITLE
Bug: Code 410

### ISSUE THREAD

**Issue by zTopCounter** [eritislami/evobot#962]
MinigetError: Status code: 410
    at ClientRequest.<anonymous> (/home/runner/ProMusic/node_modules/miniget/dist/index.js:196:27)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at TLSSocket.socketOnData (_http_client.js:474:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at TLSSocket.Readable.push (_stream_readable.js:213:10) {
  statusCode: 410

**Comment by DanielRourke** [comment]
Same error related to age restricted videos

**Comment by drewburr** [comment]
@zTopCounter what version of Evobot are you running? Could we get instructions on how to reproduce this issue? Thank you!

**Comment by DanielRourke** [comment]
I received this error with age restricted videos, once adding cookies/youtube tokens to the play requests to ytdl. However i did have to edit the download function in ytdl-core-discord to pass along the options. This was with the most current version i could clone a couple days ago.

**Comment by eritislami** [comment]
Can't play age restricted youtube videos.
