### ISSUE TITLE
Bug: When the bot plays a song for a while it will crash like this

### ISSUE THREAD

**Issue by kurumicute** [eritislami/evobot#978]
**How To Reproduce**
When the bot plays a song for a while. It will crash like this
**Expected behavior**
`events.js:353
      throw er; // Unhandled 'error' event
      ^

RangeError: offset is out of bounds
    at Uint16Array.set (<anonymous>)
    at OpusScript.encode (/home/container/node_modules/opusscript/index.js:67:16)
    at Encoder._encode (/home/container/node_modules/prism-media/src/opus/Opus.js:60:25)
    at Encoder._transform (/home/container/node_modules/prism-media/src/opus/Opus.js:157:24)
    at Encoder.Transform._read (internal/streams/transform.js:205:10)
    at Encoder.Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Encoder.Writable.write (internal/streams/writable.js:303:10)
    at VolumeTransformer.ondata (internal/streams/readable.js:745:22)
    at VolumeTransformer.emit (events.js:376:20)
Emitted 'error' event on Decoder instance at:
    at Decoder.onerror (internal/streams/readable.js:764:14)
    at Decoder.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)`

**Environment (add if possible)**
* Node.js version: 16.10.0

**Additional information & screenshots**
![image](https://user-images.githubusercontent.com/90886946/135760729-0e6f25bb-12c9-4b91-9866-f6f5c3a10272.png)

**Comment by eritislami** [comment]
It's a library error, not from the bot, I'm not the guy that maintains opusscript, can't do anything about it
